"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, LoaderCircle, Users } from "lucide-react";

export default function DesignPartnersPage() {
  const [form, setForm] = useState({ name: "", work_email: "", company: "", team_size: "2-10", extension_count: "10-50", current_process: "" }); const [state, setState] = useState<"idle"|"loading"|"done"|"error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setState("loading"); const response = await fetch("/api/design-partners", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) { setState("error"); setMessage(body.error || "Submission failed."); } else { setState("done"); setMessage("Request received. The next step is a focused workflow review, not a sales presentation."); } }
  const field = (name: keyof typeof form) => ({ value: form[name], onChange: (event: React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>) => setForm({ ...form, [name]: event.target.value }) });
  return <main className="partnerPage"><section className="partnerHero"><div><span>Design partner program</span><h1>Help validate extension intelligence on real workflows.</h1><p>For security practitioners and maintainers willing to test scan quality, report clarity and version-change monitoring against extensions they already understand.</p><div><strong><Check/> Direct product access</strong><strong><Check/> Your extensions as validation cases</strong><strong><Check/> A direct line for evidence-quality feedback</strong></div></div><aside><Users/><strong>This is a research collaboration.</strong><p>No payment details, sales qualification or automated marketing sequence.</p><Link href="/settings">Review the trust model <ArrowRight/></Link></aside></section><section className="partnerLayout"><div><span>Good fit</span><h2>You can challenge the scanner with known behavior.</h2><p>Useful partners can explain what an extension is supposed to do and help distinguish expected capabilities, risky implementation choices and genuinely suspicious evidence.</p></div>{state === "done" ? <div className="partnerSuccess"><Check/><h2>Request received.</h2><p>{message}</p><Link href="/catalog">Continue exploring the catalog <ArrowRight/></Link></div> : <form className="partnerForm" onSubmit={submit}><label><span>Name</span><input required {...field("name")}/></label><label><span>Work email</span><input type="email" required {...field("work_email")}/></label><label><span>Company or project</span><input required {...field("company")}/></label><div><label><span>Team size</span><select {...field("team_size")}><option>2-10</option><option>11-50</option><option>51-250</option><option>251+</option></select></label><label><span>Extensions in use</span><select {...field("extension_count")}><option>Under 10</option><option>10-50</option><option>51-200</option><option>200+</option></select></label></div><label><span>What behavior or extensions can you help validate?</span><textarea rows={5} {...field("current_process")}/></label><button className="button buttonDark" disabled={state === "loading"}>{state === "loading" ? <><LoaderCircle className="spin"/> Sending</> : <>Request design partnership <ArrowRight/></>}</button>{message ? <p className="partnerError">{message}</p> : null}<small>No payment information. No automated marketing sequence.</small></form>}</section></main>;
}
