"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, LoaderCircle, ShieldCheck, Users } from "lucide-react";

export default function DesignPartnersPage() {
  const [form, setForm] = useState({ name: "", work_email: "", company: "", team_size: "2-10", extension_count: "10-50", current_process: "" }); const [state, setState] = useState<"idle"|"loading"|"done"|"error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setState("loading"); const response = await fetch("/api/design-partners", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) { setState("error"); setMessage(body.error || "Submission failed."); } else { setState("done"); setMessage("Request received. The next step is a focused workflow review, not a sales presentation."); } }
  const field = (name: keyof typeof form) => ({ value: form[name], onChange: (event: React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>) => setForm({ ...form, [name]: event.target.value }) });
  return <main className="partnerPage"><section className="partnerHero"><div><span>Design partner program</span><h1>Shape extension security around a real developer fleet.</h1><p>For security and engineering teams that need visibility into VS Code, Cursor, Windsurf, or VSCodium extensions today.</p><div><strong><Check/> Direct product access</strong><strong><Check/> Your extension inventory as the test case</strong><strong><Check/> Influence over policy and monitoring workflows</strong></div></div><aside><Users/><strong>This is not a paid-plan waitlist.</strong><p>The program validates whether continuous extension inventory, version monitoring, and team decisions solve a real operational problem.</p><Link href="/settings">Review the architecture <ArrowRight/></Link></aside></section><section className="partnerLayout"><div><span>Good fit</span><h2>Teams with an extension decision problem.</h2><p>You know developers install privileged IDE tooling, but inventory is incomplete, approval is informal, or updates change access without a new review.</p><div className="partnerOutcomes"><article><ShieldCheck/><strong>Establish the inventory</strong><p>Identify the exact extensions and versions used across developer environments.</p></article><article><ShieldCheck/><strong>Define the policy</strong><p>Separate approved, review-required, blocked, and incomplete artifacts.</p></article><article><ShieldCheck/><strong>Monitor the change</strong><p>Bring new capabilities, dependencies, files, and alerts back into review.</p></article></div></div>{state === "done" ? <div className="partnerSuccess"><Check/><h2>Request received.</h2><p>{message}</p><Link href="/catalog">Continue exploring the catalog <ArrowRight/></Link></div> : <form className="partnerForm" onSubmit={submit}><label><span>Name</span><input required {...field("name")}/></label><label><span>Work email</span><input type="email" required {...field("work_email")}/></label><label><span>Company or project</span><input required {...field("company")}/></label><div><label><span>Team size</span><select {...field("team_size")}><option>2-10</option><option>11-50</option><option>51-250</option><option>251+</option></select></label><label><span>Extensions in use</span><select {...field("extension_count")}><option>Under 10</option><option>10-50</option><option>51-200</option><option>200+</option></select></label></div><label><span>How are extension decisions handled today?</span><textarea rows={5} {...field("current_process")}/></label><button className="button buttonDark" disabled={state === "loading"}>{state === "loading" ? <><LoaderCircle className="spin"/> Sending</> : <>Request design partnership <ArrowRight/></>}</button>{message ? <p className="partnerError">{message}</p> : null}<small>No payment information. No automated marketing sequence.</small></form>}</section></main>;
}
