"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, Bell, Check, Mail, Plus, Settings2, ShieldCheck } from "lucide-react";
import { browserDb } from "@/lib/supabase";

type Watchlist = { id: string; name: string; watchlist_items?: Array<{ extension_id: string; created_at: string; extensions?: { display_name?: string; icon_url?: string } }> };
type Preferences = { in_app_enabled: boolean; email_digest: "off" | "daily" | "weekly"; minimum_severity: string; release_alerts: boolean; scan_alerts: boolean };
const defaultPreferences: Preferences = { in_app_enabled: true, email_digest: "off", minimum_severity: "MEDIUM", release_alerts: true, scan_alerts: true };

export default function MonitorPage() {
  const db = useMemo(() => browserDb(), []); const [lists, setLists] = useState<Watchlist[]>([]); const [preferences, setPreferences] = useState<Preferences>(defaultPreferences); const [name, setName] = useState(""); const [state, setState] = useState<"loading" | "ready" | "signed-out" | "error">("loading"); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { if (!db) return setState("error"); const { data: { user } } = await db.auth.getUser(); if (!user) return setState("signed-out"); const [watch, preference] = await Promise.all([db.from("watchlists").select("*,watchlist_items(extension_id,created_at,extensions(display_name,icon_url))").order("created_at"), db.from("monitoring_preferences").select("in_app_enabled,email_digest,minimum_severity,release_alerts,scan_alerts").maybeSingle()]); if (watch.error || preference.error) return setState("error"); setLists(watch.data || []); setPreferences(preference.data || defaultPreferences); setState("ready"); }, [db]);
  useEffect(() => { void load(); }, [load]);
  async function createList() { if (!db || !name.trim()) return; const { data: { user } } = await db.auth.getUser(); if (!user) return; const result = await db.from("watchlists").insert({ owner_id: user.id, name: name.trim().slice(0, 80) }); if (!result.error) { setName(""); void load(); } }
  async function savePreferences(next: Preferences) { if (!db) return; setPreferences(next); setSaving(true); const { data: { user } } = await db.auth.getUser(); if (user) await db.from("monitoring_preferences").upsert({ owner_id: user.id, ...next, updated_at: new Date().toISOString() }); setSaving(false); }
  if (state === "signed-out") return <main className="workspacePage"><section className="workspaceSignedOut"><Bell/><span>Monitor · release tracking</span><h1>Watch the release. We do the next scan.</h1><p>Free sign-in unlocks private watchlists and an in-product alert queue. Public extension reports remain open to everyone.</p><Link className="button buttonDark" href="/account?next=/monitor">Create free workspace <ArrowRight/></Link></section></main>;
  if (state === "error") return <main className="workspacePage"><section className="workspaceSignedOut"><Bell/><span>Monitor</span><h1>Monitoring is temporarily unavailable.</h1><p>Please refresh shortly. Public reports are unaffected.</p></section></main>;
  return <main className="workspacePage monitorPage"><section className="workspaceHead"><div><span>Monitor · watched releases</span><h1>Follow extensions after approval.</h1><p>When a watched extension publishes a new artifact, IDE Scanner creates a release event, queues Deep Scan, and adds the completed evidence to your private dashboard.</p></div><div className="workspaceActions"><Link className="button buttonDark" href="/catalog">Find an extension <ArrowRight/></Link><Link className="button buttonQuiet" href="/workspace">Open dashboard</Link></div></section>{state === "loading" ? <div className="workspaceMessage">Loading monitored extensions…</div> : null}
    <section className="monitorHow"><span>How monitoring works</span><ol><li><strong>Detect</strong><p>Catalog refresh notices a newly published version.</p></li><li><strong>Analyze</strong><p>Deep Scan is queued for the exact new artifact.</p></li><li><strong>Decide</strong><p>Your dashboard receives severity-led evidence and an operational action.</p></li></ol></section>
    <section className="workspaceSection"><div className="workspaceSectionHead"><div><span>Watchlists</span><h2>Extensions you follow</h2></div><div className="createRow"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="New watchlist" aria-label="New watchlist name"/><button className="iconButton" onClick={() => void createList()} title="Create watchlist" aria-label="Create watchlist"><Plus/></button></div></div><div className="watchlistBlocks">{lists.map((list) => <article key={list.id}><header><div><strong>{list.name}</strong><span>{list.watchlist_items?.length || 0} extensions</span></div><Bell/></header>{list.watchlist_items?.map((item) => <Link key={item.extension_id} href={`/extensions/${encodeURIComponent(item.extension_id)}`}><span>{item.extensions?.display_name || item.extension_id}</span><code>{item.extension_id}</code><ArrowRight/></Link>)}{!list.watchlist_items?.length ? <p>Add an extension from its intelligence page.</p> : null}</article>)}{state === "ready" && !lists.length ? <article><header><div><strong>No watchlist yet</strong><span>Start with one extension</span></div></header><p>Choose a published extension, then select Watch releases from its intelligence page.</p></article> : null}</div></section>
    <section className="workspaceSection preferences"><div className="workspaceSectionHead"><div><span>Notification settings</span><h2>Control the signal</h2></div><span className="saveState">{saving ? "Saving…" : "Saved"}</span></div><div className="preferenceGrid"><label><span><Bell/> In-product inbox</span><input type="checkbox" checked={preferences.in_app_enabled} onChange={(event) => void savePreferences({ ...preferences, in_app_enabled: event.target.checked })}/><p>Private release and scan events appear on your Dashboard.</p></label><label><span><Check/> Release events</span><input type="checkbox" checked={preferences.release_alerts} onChange={(event) => void savePreferences({ ...preferences, release_alerts: event.target.checked })}/><p>Notify when a watched extension publishes a new version.</p></label><label><span><ShieldCheck/> Scan evidence</span><input type="checkbox" checked={preferences.scan_alerts} onChange={(event) => void savePreferences({ ...preferences, scan_alerts: event.target.checked })}/><p>Notify when Deep Scan completes or coverage is incomplete.</p></label><label><span><Settings2/> Minimum severity</span><select value={preferences.minimum_severity} onChange={(event) => void savePreferences({ ...preferences, minimum_severity: event.target.value })}>{["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"].map((item) => <option key={item}>{item}</option>)}</select><p>Applied to future delivery channels as they are enabled.</p></label><label className="emailPreference"><span><Mail/> Email digest</span><select value={preferences.email_digest} onChange={(event) => void savePreferences({ ...preferences, email_digest: event.target.value as Preferences["email_digest"] })}><option value="off">Off</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select><p>Email delivery is not enabled in this workspace yet. This setting is saved, but no message will be sent until a verified delivery provider is configured.</p></label></div></section>
  </main>;
}
