"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, Bell, Check, MessageSquare, Pencil, Plus, Search, Settings2, ShieldCheck, Trash2, X } from "lucide-react";
import { browserDb } from "@/lib/supabase";
import ExtensionIcon from "@/app/ExtensionIcon";

type Watchlist = { id: string; name: string; watchlist_items?: Array<{ extension_id: string; created_at: string; extensions?: { display_name?: string; icon_url?: string } }> };
type Preferences = { in_app_enabled: boolean; email_digest: "off" | "daily" | "weekly"; minimum_severity: string; release_alerts: boolean; scan_alerts: boolean };
type Channel = { id: string; kind: string; label: string; enabled: boolean; minimum_severity: string; last_validated_at?: string | null; last_error?: string | null };
type MarketplaceMatch = { extension_id: string; display_name: string; publisher: string; version: string; icon_url?: string; description?: string };
const defaultPreferences: Preferences = { in_app_enabled: true, email_digest: "off", minimum_severity: "MEDIUM", release_alerts: true, scan_alerts: true };

export default function MonitorPage() {
  const db = useMemo(() => browserDb(), []); const [lists, setLists] = useState<Watchlist[]>([]); const [preferences, setPreferences] = useState<Preferences>(defaultPreferences); const [channels, setChannels] = useState<Channel[]>([]); const [deliveryConfigured, setDeliveryConfigured] = useState(false); const [slackUrl, setSlackUrl] = useState(""); const [channelLabel, setChannelLabel] = useState("Security alerts"); const [channelError, setChannelError] = useState(""); const [name, setName] = useState(""); const [query, setQuery] = useState(""); const [matches, setMatches] = useState<MarketplaceMatch[]>([]); const [searching, setSearching] = useState(false); const [adding, setAdding] = useState(""); const [state, setState] = useState<"loading" | "ready" | "signed-out" | "error">("loading"); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { if (!db) return setState("error"); const { data: { user } } = await db.auth.getUser(); if (!user) return setState("signed-out"); const session = await db.auth.getSession(); const token = session.data.session?.access_token || ""; const [watch, preference, channelResponse] = await Promise.all([db.from("watchlists").select("*,watchlist_items(extension_id,created_at,extensions(display_name,icon_url))").order("created_at"), db.from("monitoring_preferences").select("in_app_enabled,email_digest,minimum_severity,release_alerts,scan_alerts").maybeSingle(), fetch("/api/notification-channels", { headers: { Authorization: `Bearer ${token}` } })]); if (watch.error || preference.error) return setState("error"); const channelBody = channelResponse.ok ? await channelResponse.json() : { channels: [], configured: false }; setLists(watch.data || []); setPreferences(preference.data || defaultPreferences); setChannels(channelBody.channels || []); setDeliveryConfigured(Boolean(channelBody.configured)); setState("ready"); }, [db]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const value = query.trim(); const timer = window.setTimeout(() => { if (value.length < 2) { setMatches([]); return; } setSearching(true); void fetch(`/api/marketplace/search?q=${encodeURIComponent(value)}`).then(async (response) => response.ok ? response.json() : { results: [] }).then((body) => setMatches(Array.isArray(body.results) ? body.results.slice(0, 6) : [])).catch(() => setMatches([])).finally(() => setSearching(false)); }, value.length < 2 ? 0 : 250); return () => window.clearTimeout(timer); }, [query]);
  async function createList() { if (!db || !name.trim()) return; const { data: { user } } = await db.auth.getUser(); if (!user) return; const result = await db.from("watchlists").insert({ owner_id: user.id, name: name.trim().slice(0, 80) }); if (!result.error) { setName(""); void load(); } }
  async function accessToken() { const session = await db?.auth.getSession(); return session?.data.session?.access_token || ""; }
  async function renameList(list: Watchlist) { const next = window.prompt("Rename watchlist", list.name)?.trim(); if (!next || next === list.name) return; const token = await accessToken(); const response = await fetch(`/api/watchlists/${list.id}`, { method: "PATCH", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ name: next }) }); if (response.ok) void load(); }
  async function deleteList(list: Watchlist) { if (!window.confirm(`Delete “${list.name}” and remove its monitored extensions?`)) return; const token = await accessToken(); const response = await fetch(`/api/watchlists/${list.id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); if (response.ok) void load(); }
  async function removeItem(listId: string, extensionId: string) { if (!window.confirm(`Stop monitoring ${extensionId} in this watchlist?`)) return; const token = await accessToken(); const response = await fetch(`/api/watchlists/${listId}/items?extension_id=${encodeURIComponent(extensionId)}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); if (response.ok) void load(); }
  async function addItem(listId: string, extensionId: string) { setAdding(extensionId); const token = await accessToken(); const response = await fetch(`/api/watchlists/${listId}/items`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ extension_id: extensionId }) }); setAdding(""); if (response.ok) { setQuery(""); setMatches([]); void load(); } }
  async function savePreferences(next: Preferences) { if (!db) return; setPreferences(next); setSaving(true); const { data: { user } } = await db.auth.getUser(); if (user) await db.from("monitoring_preferences").upsert({ owner_id: user.id, ...next, updated_at: new Date().toISOString() }); setSaving(false); }
  async function connectSlack() { setChannelError(""); if (!slackUrl.trim()) return setChannelError("Paste a Slack incoming webhook URL."); setSaving(true); const token = await accessToken(); const response = await fetch("/api/notification-channels", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ label: channelLabel, webhook_url: slackUrl, minimum_severity: preferences.minimum_severity }) }); const body = await response.json(); setSaving(false); if (!response.ok) return setChannelError(String(body.error || "Slack connection failed.")); setSlackUrl(""); await load(); }
  async function removeChannel(id: string) { if (!window.confirm("Disconnect this Slack destination?")) return; const token = await accessToken(); const response = await fetch(`/api/notification-channels?id=${encodeURIComponent(id)}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); if (response.ok) await load(); }
  if (state === "signed-out") return <main className="workspacePage gatePage"><section className="workspaceSignedOut"><Bell/><span>Monitor · release tracking</span><h1>Watch the release. We do the next scan.</h1><p>Free sign-in unlocks private watchlists, automatic exact-version analysis, an in-product queue, and optional Slack delivery. Public reports remain open to everyone.</p><Link className="button buttonDark" href="/account?next=/monitor">Create free workspace <ArrowRight/></Link></section><section className="gatePreview monitorGatePreview" aria-label="Monitoring workflow preview"><header><span>Release monitor</span><strong>A return loop with an observable state</strong></header><div><article><i>WATCHING</i><Check/><strong>Registry polling active</strong><p>Marketplace and Open VSX releases are checked on schedule.</p></article><article><i>QUEUED</i><ShieldCheck/><strong>Deep Scan follows change</strong><p>The new version gets its own artifact hash and report.</p></article><article><i>DELIVERED</i><MessageSquare/><strong>Dashboard + Slack</strong><p>Only evidence meeting your threshold leaves the product.</p></article></div></section></main>;
  if (state === "error") return <main className="workspacePage"><section className="workspaceSignedOut"><Bell/><span>Monitor</span><h1>Monitoring is temporarily unavailable.</h1><p>Please refresh shortly. Public reports are unaffected.</p></section></main>;
  return <main className="workspacePage monitorPage"><section className="workspaceHead"><div><span>Monitor · watched releases</span><h1>Follow extensions after approval.</h1><p>When a watched extension publishes a new artifact, GUARDRAILS creates a release event, queues Deep Scan, and adds the completed evidence to your private dashboard.</p></div><div className="workspaceActions"><Link className="button buttonDark" href="/catalog">Find an extension <ArrowRight/></Link><Link className="button buttonQuiet" href="/workspace">Open dashboard</Link></div></section>{state === "loading" ? <div className="workspaceMessage">Loading monitored extensions…</div> : null}
    <section className="monitorHow"><span>How monitoring works</span><ol><li><strong>Detect</strong><p>Catalog refresh notices a newly published version.</p></li><li><strong>Analyze</strong><p>Deep Scan is queued for the exact new artifact.</p></li><li><strong>Decide</strong><p>Your dashboard receives severity-led evidence and an operational action.</p></li></ol></section>
    <section className="workspaceSection"><div className="workspaceSectionHead"><div><span>Watchlists</span><h2>Extensions you follow</h2></div><div className="createRow"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="New watchlist" aria-label="New watchlist name"/><button className="iconButton" onClick={() => void createList()} title="Create watchlist" aria-label="Create watchlist"><Plus/></button></div></div><div className="watchlistSearch"><Search/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Marketplace or Open VSX to add an extension" aria-label="Search extensions to add to a watchlist"/>{searching ? <span>Searching…</span> : null}</div>{matches.length ? <div className="watchlistMatches">{matches.map((match) => <article key={match.extension_id}><ExtensionIcon iconUrl={match.icon_url} publisher={match.publisher} name={match.display_name} size="logo"/><div><strong>{match.display_name}</strong><code>{match.extension_id}@{match.version}</code><p>{match.description || match.publisher}</p></div><div>{lists.map((list) => <button key={list.id} onClick={() => void addItem(list.id, match.extension_id)} disabled={adding === match.extension_id}>{adding === match.extension_id ? "Adding…" : `Add to ${list.name}`}</button>)}</div></article>)}</div> : null}<div className="watchlistBlocks">{lists.map((list) => <article key={list.id}><header><div><strong>{list.name}</strong><span>{list.watchlist_items?.length || 0} extensions</span></div><div className="watchlistActions"><button onClick={() => void renameList(list)} aria-label={`Rename ${list.name}`} title="Rename watchlist"><Pencil/></button><button onClick={() => void deleteList(list)} aria-label={`Delete ${list.name}`} title="Delete watchlist"><Trash2/></button></div></header>{list.watchlist_items?.map((item) => <div className="watchlistItem" key={item.extension_id}><Link href={`/extensions/${encodeURIComponent(item.extension_id)}`}><ExtensionIcon iconUrl={item.extensions?.icon_url} publisher={item.extension_id} name={item.extensions?.display_name || item.extension_id} size="logo"/><span><strong>{item.extensions?.display_name || item.extension_id}</strong><code>{item.extension_id}</code></span><ArrowRight/></Link><button onClick={() => void removeItem(list.id, item.extension_id)} aria-label={`Remove ${item.extension_id}`} title="Stop monitoring"><X/></button></div>)}{!list.watchlist_items?.length ? <p>Search the registry above and add an extension directly to this watchlist.</p> : null}</article>)}{state === "ready" && !lists.length ? <article><header><div><strong>No watchlist yet</strong><span>Create one above, then search real registry extensions here.</span></div></header></article> : null}</div></section>
    <section className="workspaceSection preferences"><div className="workspaceSectionHead"><div><span>Notification settings</span><h2>Control the signal</h2></div><span className="saveState">{saving ? "Saving…" : "Saved"}</span></div><div className="preferenceGrid"><label><span><Bell/> In-product inbox</span><input type="checkbox" checked={preferences.in_app_enabled} onChange={(event) => void savePreferences({ ...preferences, in_app_enabled: event.target.checked })}/><p>Private release and scan events appear on your Dashboard.</p></label><label><span><Check/> Release events</span><input type="checkbox" checked={preferences.release_alerts} onChange={(event) => void savePreferences({ ...preferences, release_alerts: event.target.checked })}/><p>Notify when a watched extension publishes a new version.</p></label><label><span><ShieldCheck/> Scan evidence</span><input type="checkbox" checked={preferences.scan_alerts} onChange={(event) => void savePreferences({ ...preferences, scan_alerts: event.target.checked })}/><p>Notify when Deep Scan completes or coverage is incomplete.</p></label><label><span><Settings2/> Minimum severity</span><select value={preferences.minimum_severity} onChange={(event) => void savePreferences({ ...preferences, minimum_severity: event.target.value })}>{["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"].map((item) => <option key={item}>{item}</option>)}</select><p>New outbound channels inherit this threshold.</p></label></div></section>
    <section className="workspaceSection deliveryChannels"><div className="workspaceSectionHead"><div><span>Outbound delivery</span><h2>Send actionable alerts to Slack</h2></div><MessageSquare/></div><p className="sectionIntro">Add an incoming webhook from a channel you control. The endpoint is encrypted at rest, tested once when connected, and never returned to the browser.</p><div className="channelRows">{channels.map((channel) => <article key={channel.id}><div><MessageSquare/><span><strong>{channel.label}</strong><small>Slack · {channel.minimum_severity} and above{channel.last_validated_at ? " · connected" : ""}</small></span></div><button onClick={() => void removeChannel(channel.id)} aria-label={`Disconnect ${channel.label}`}><Trash2/> Disconnect</button></article>)}</div>{deliveryConfigured ? <div className="channelForm"><label><span>Channel name</span><input value={channelLabel} onChange={(event) => setChannelLabel(event.target.value)} placeholder="Security alerts"/></label><label><span>Slack incoming webhook</span><input type="password" value={slackUrl} onChange={(event) => setSlackUrl(event.target.value)} placeholder="https://hooks.slack.com/services/…" autoComplete="off"/></label><button className="button buttonDark" onClick={() => void connectSlack()} disabled={saving}>Connect & test</button></div> : <div className="integrationUnavailable">Outbound delivery is not configured by the service operator. In-product alerts continue to work.</div>}{channelError ? <p className="previewError">{channelError}</p> : null}</section>
  </main>;
}
