"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, AtSign, Check, Code2, LoaderCircle, LockKeyhole, LogOut, ShieldCheck } from "lucide-react";
import { browserDb } from "@/lib/supabase";

type AccountState = { email: string; token: string; profile: Record<string, unknown> | null };
export default function AccountPage() {
  const db = useMemo(() => browserDb(), []); const [email, setEmail] = useState(""); const [account, setAccount] = useState<AccountState | null>(null); const [loading, setLoading] = useState(Boolean(db)); const [message, setMessage] = useState("");
  const [role, setRole] = useState("developer"); const [ide, setIde] = useState("vscode"); const [useCase, setUseCase] = useState("personal");
  useEffect(() => { if (!db) return; void db.auth.getSession().then(async ({ data }) => { const session = data.session; if (!session) { setLoading(false); return; } const response = await fetch("/api/profile", { headers: { Authorization: `Bearer ${session.access_token}` } }); const body = await response.json(); setAccount({ email: session.user.email || "", token: session.access_token, profile: body.profile || null }); setLoading(false); }); }, [db]);
  function callbackUrl() { return `${window.location.origin}/account${window.location.search}`; }
  function continueToDestination() { const destination = new URLSearchParams(window.location.search).get("next"); window.location.assign(destination?.startsWith("/") && !destination.startsWith("//") ? destination : "/workspace"); }
  async function oauth(provider: "github"|"google") { if (!db) return setMessage("Supabase Auth is not connected to this deployment."); await db.auth.signInWithOAuth({ provider, options: { redirectTo: callbackUrl() } }); }
  async function magicLink() { if (!db) return setMessage("Supabase Auth is not connected to this deployment."); if (!email.trim()) return setMessage("Enter an email address."); const result = await db.auth.signInWithOtp({ email, options: { emailRedirectTo: callbackUrl() } }); setMessage(result.error?.message || "Check your inbox for the secure sign-in link."); }
  async function finishOnboarding() { if (!account) return; const response = await fetch("/api/profile", { method: "PATCH", headers: { Authorization: `Bearer ${account.token}`, "Content-Type": "application/json" }, body: JSON.stringify({ role, primary_ide: ide, use_case: useCase }) }); const body = await response.json(); if (!response.ok) return setMessage(body.error); setAccount({ ...account, profile: body.profile }); continueToDestination(); }
  async function signOut() { await db?.auth.signOut(); setAccount(null); }
  if (loading) return <main className="authProductPage"><div className="authLoading"><LoaderCircle className="spin"/> Opening secure session…</div></main>;
  if (account && !account.profile?.onboarding_completed) return <main className="authProductPage"><section className="onboardingIntro"><span>One-minute setup</span><h1>Make the first decision relevant.</h1><p>IDE Scanner uses this only to organize the workspace and recommended workflows. Scanner results do not change by role.</p></section><section className="onboardingForm"><Choice label="Your role" value={role} setValue={setRole} options={[["developer","Developer"],["security","Security engineer"],["engineering_leader","Engineering leader"]]}/><Choice label="Primary IDE" value={ide} setValue={setIde} options={[["vscode","VS Code"],["cursor","Cursor"],["windsurf","Windsurf"],["vscodium","VSCodium"],["other","Other"]]}/><Choice label="How you will use it" value={useCase} setValue={setUseCase} options={[["personal","Personal decisions"],["team","Team extension policy"]]}/><button className="button buttonDark" onClick={() => void finishOnboarding()}>Open my workspace <ArrowRight/></button>{message ? <p>{message}</p> : null}</section></main>;
  if (account) return <main className="authProductPage"><section className="signedInProduct"><div><span><ShieldCheck/> Signed in</span><h1>Your extension security workspace.</h1><p>{account.email}</p></div><button className="button buttonQuiet" onClick={() => void signOut()}><LogOut/> Sign out</button></section><section className="accountNextSteps"><Link href="/workspace"><RadarIcon/><div><span>Monitoring</span><strong>Open watchlists and extension changes</strong><p>Return to decisions that need attention.</p></div><ArrowRight/></Link><Link href="/catalog"><ShieldCheck/><div><span>Public intelligence</span><strong>Find an extension to monitor</strong><p>Start from a published artifact and exact version.</p></div><ArrowRight/></Link></section></main>;
  return <main className="authProductPage"><section className="authValue"><div><span>Free personal workspace</span><h1>Keep watching after the first scan.</h1><p>Save extensions, follow new releases, and preserve the reason behind every install decision.</p><ul><li><Check/> Public catalog and exact-version intelligence</li><li><Check/> Personal extension watchlist</li><li><Check/> Version-change monitoring</li><li><Check/> Team-ready review history</li></ul></div><aside><LockKeyhole/><strong>Your source code is not part of sign-in.</strong><p>Authentication protects workspace and team data. Public extension analysis remains public.</p></aside></section><section className="oauthPanel"><div><span>Continue to IDE Scanner</span><h2>No password to remember.</h2></div><button className="oauthButton github" onClick={() => void oauth("github")}><Code2/> Continue with GitHub <ArrowRight/></button><button className="oauthButton google" onClick={() => void oauth("google")}><b>G</b> Continue with Google <ArrowRight/></button><div className="authDivider"><span>or use a secure email link</span></div><label className="magicLink"><AtSign/><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@company.com"/><button onClick={() => void magicLink()}>Email link</button></label>{message ? <p className="authMessage">{message}</p> : null}<small>By continuing, you agree to use the service responsibly. Public extension intelligence remains available without an account.</small></section></main>;
}
function Choice({ label, value, setValue, options }: { label: string; value: string; setValue: (value: string) => void; options: string[][] }) { return <fieldset><legend>{label}</legend><div>{options.map(([id, text]) => <button type="button" className={value === id ? "selected" : ""} key={id} onClick={() => setValue(id)}>{value === id ? <Check/> : null}{text}</button>)}</div></fieldset>; }
function RadarIcon() { return <div className="radarIcon"><i/><span/></div>; }
