"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, AtSign, Check, LoaderCircle, LockKeyhole, LogOut, ShieldCheck } from "lucide-react";
import { browserDb } from "@/lib/supabase";
import { isEmailOtp, normalizeEmail, normalizeEmailOtp } from "@/lib/emailOtp";
import { trackProductEvent } from "@/lib/analyticsEvents";

type AccountState = { email: string; token: string; profile: Record<string, unknown> | null };
const googleEnabled = process.env.NEXT_PUBLIC_GOOGLE_AUTH_ENABLED === "true";
const githubEnabled = process.env.NEXT_PUBLIC_GITHUB_AUTH_ENABLED === "true";
export default function AccountPage() {
  const db = useMemo(() => browserDb(), []); const [email, setEmail] = useState(""); const [emailOtp, setEmailOtp] = useState(""); const [emailOtpSent, setEmailOtpSent] = useState(false); const [emailAuthPending, setEmailAuthPending] = useState(false); const [account, setAccount] = useState<AccountState | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const [role, setRole] = useState("developer"); const [ide, setIde] = useState("vscode");
  const destination = typeof window === "undefined" ? "/workspace" : new URLSearchParams(window.location.search).get("next") || "/workspace";
  const entryPoint = destination.startsWith("/monitor") ? "monitor" : destination.startsWith("/extensions/") ? "report" : "account" as const;
  const resumeLabel = entryPoint === "monitor" ? "Continue to monitor this extension." : entryPoint === "report" ? "Continue with this exact public report." : "Continue to your workspace.";
  useEffect(() => { if (!db) { const timer = window.setTimeout(() => setLoading(false), 0); return () => window.clearTimeout(timer); } void db.auth.getSession().then(async ({ data }) => { const session = data.session; if (!session) { setLoading(false); return; } const response = await fetch("/api/profile", { headers: { Authorization: `Bearer ${session.access_token}` } }); const body = await response.json(); setAccount({ email: session.user.email || "", token: session.access_token, profile: body.profile || null }); setLoading(false); }).catch(() => setLoading(false)); }, [db]);
  useEffect(() => { const error = new URLSearchParams(window.location.search).get("error"); const text = error === "invalid_link" ? "That sign-in link is invalid or expired. Start a new sign-in." : error === "missing_code" ? "The sign-in response was incomplete. Start again." : ""; if (!text) return; const timer = window.setTimeout(() => setMessage(text), 0); return () => window.clearTimeout(timer); }, []);
  function callbackUrl() { const destination = new URLSearchParams(window.location.search).get("next") || "/workspace"; const configured = process.env.NEXT_PUBLIC_SITE_URL; const origin = window.location.hostname === "localhost" ? window.location.origin : configured || window.location.origin; return `${origin}/auth/callback?next=${encodeURIComponent(destination)}`; }
  function continueToDestination() { const destination = new URLSearchParams(window.location.search).get("next"); window.location.assign(destination?.startsWith("/") && !destination.startsWith("//") ? destination : "/workspace"); }
  async function oauth(provider: "google" | "github") { if (!db) return setMessage("Sign-in is temporarily unavailable. Public extension intelligence remains accessible."); trackProductEvent({ name: "workspace_signup_started", source_route: window.location.pathname, entry_point: entryPoint }); const result = await db.auth.signInWithOAuth({ provider, options: { redirectTo: callbackUrl() } }); if (result.error) setMessage(result.error.message); }
  async function sendEmailOtp() { const address = normalizeEmail(email); if (!db) return setMessage("Supabase Auth is not connected to this deployment."); if (!address) return setMessage("Enter an email address."); trackProductEvent({ name: "workspace_signup_started", source_route: window.location.pathname, entry_point: entryPoint }); setEmailAuthPending(true); const result = await db.auth.signInWithOtp({ email: address, options: { shouldCreateUser: true, emailRedirectTo: callbackUrl() } }); setEmailAuthPending(false); if (result.error) return setMessage(result.error.message); setEmail(address); setEmailOtp(""); setEmailOtpSent(true); setMessage("Enter the six-digit code we sent to your email."); }
  async function verifyEmailOtp() { const address = normalizeEmail(email); if (!db) return setMessage("Supabase Auth is not connected to this deployment."); if (!isEmailOtp(emailOtp)) return setMessage("Enter the complete six-digit code."); setEmailAuthPending(true); const result = await db.auth.verifyOtp({ email: address, token: emailOtp, type: "email" }); setEmailAuthPending(false); if (result.error) return setMessage("That code is invalid or expired. Request a new one."); continueToDestination(); }
  async function finishOnboarding() { if (!account) return; const response = await fetch("/api/profile", { method: "PATCH", headers: { Authorization: `Bearer ${account.token}`, "Content-Type": "application/json" }, body: JSON.stringify({ role, primary_ide: ide, use_case: "personal" }) }); const body = await response.json(); if (!response.ok) return setMessage(body.error); setAccount({ ...account, profile: body.profile }); continueToDestination(); }
  async function signOut() { await db?.auth.signOut(); setAccount(null); }
  if (loading) return <main className="authProductPage"><div className="authLoading"><LoaderCircle className="spin"/> Opening secure session…</div></main>;
  if (account && !account.profile?.onboarding_completed) return <main className="authProductPage onboardingPage"><section className="onboardingIntro"><span>One-minute setup</span><h1>Make your workspace work for you.</h1><p>Choose a role and primary editor so GuardRails can organize your workspace around the decisions you make. Analysis results stay the same for everyone.</p><ul className="onboardingBenefits"><li>Keep extension decisions in one place</li><li>Follow the releases your team uses</li><li>Return to this analysis when setup is complete</li></ul></section><section className="onboardingForm" aria-label="Personal workspace setup"><div className="onboardingFormIntro"><span>Personal setup</span><h2>Two quick choices</h2><p>You can change these preferences later.</p></div><Choice label="Your role" value={role} setValue={setRole} options={[["developer","Developer"],["security","Security engineer"],["engineering_leader","Engineering leader"]]}/><Choice label="Primary IDE" value={ide} setValue={setIde} options={[["vscode","VS Code"],["cursor","Cursor"],["windsurf","Windsurf"],["vscodium","VSCodium"],["other","Other"]]}/><button className="button buttonDark" onClick={() => void finishOnboarding()}>Open my workspace <ArrowRight/></button>{message ? <p>{message}</p> : null}</section></main>;
  if (account) return <main className="authProductPage"><section className="signedInProduct"><div><span><ShieldCheck/> Signed in</span><h1>Your Monitor workspace.</h1><p>{account.email}</p></div><button className="button buttonQuiet" onClick={() => void signOut()}><LogOut/> Sign out</button></section><section className="accountNextSteps"><Link href="/workspace"><RadarIcon/><div><span>Monitor</span><strong>Open watchlists and release changes</strong><p>Return to decisions that need attention.</p></div><ArrowRight/></Link><Link href="/registry"><ShieldCheck/><div><span>Extension Registry</span><strong>Find an extension to monitor</strong><p>Search public extension profiles and their versions.</p></div><ArrowRight/></Link></section></main>;
  return <main className="authProductPage"><section className="authValue"><div><span>Free personal workspace</span><h1>Keep watching after the first scan.</h1><p>Save extensions, follow new releases, and preserve the reason behind every install decision.</p><ul><li><Check/> Public catalog and exact-version intelligence</li><li><Check/> Personal extension watchlist</li><li><Check/> Version-change monitoring</li><li><Check/> Personal review history</li></ul></div><aside><LockKeyhole/><strong>Your source code is not part of sign-in.</strong><p>Authentication protects your personal workspace. Public extension analysis remains public.</p></aside></section><section className="oauthPanel"><div><span>Continue to GUARDRAILS</span><h2>{resumeLabel}</h2></div>{googleEnabled ? <button className="oauthButton google" onClick={() => void oauth("google")}><GoogleMark/> Continue with Google <ArrowRight/></button> : null}{githubEnabled ? <button className="oauthButton" onClick={() => void oauth("github")}><GitHubMark/> Continue with GitHub <ArrowRight/></button> : null}{googleEnabled || githubEnabled ? <div className="authDivider"><span>or use email</span></div> : null}<form className="emailOtp" onSubmit={(event) => { event.preventDefault(); void (emailOtpSent ? verifyEmailOtp() : sendEmailOtp()); }}><label><AtSign/><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@company.com" aria-label="Email address" autoComplete="email" spellCheck={false} disabled={emailAuthPending || emailOtpSent} required/></label>{emailOtpSent ? <><input className="emailOtpCode" type="text" inputMode="numeric" pattern="[0-9]{6}" value={emailOtp} onChange={(event) => setEmailOtp(normalizeEmailOtp(event.target.value))} placeholder="6-digit code" aria-label="Six-digit sign-in code" autoComplete="one-time-code" maxLength={6} required/><div className="emailOtpActions"><button type="submit" disabled={emailAuthPending}>{emailAuthPending ? "Verifying…" : "Verify code"}</button><button type="button" className="textAction" onClick={() => void sendEmailOtp()} disabled={emailAuthPending}>Send a new code</button></div></> : <button type="submit" disabled={emailAuthPending}>{emailAuthPending ? "Sending…" : "Email me a code"}</button>}</form>{message ? <p className="authMessage" role="status">{message}</p> : null}<small>By continuing, you agree to use the service responsibly. Public extension intelligence remains available without an account.</small></section></main>;
}
function GoogleMark() { return <svg className="googleMark" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.35 12.23c0-.71-.06-1.4-.18-2.05H12v3.88h5.24a4.48 4.48 0 0 1-1.94 2.94v2.51h3.23c1.89-1.74 2.82-4.3 2.82-7.28Z"/><path fill="#34A853" d="M12 21.75c2.63 0 4.84-.87 6.45-2.36L15.22 16.9c-.87.58-1.98.92-3.22.92-2.55 0-4.71-1.72-5.48-4.03H3.18v2.59A9.75 9.75 0 0 0 12 21.75Z"/><path fill="#FBBC05" d="M6.52 13.79A5.87 5.87 0 0 1 6.21 12c0-.62.11-1.23.31-1.79V7.62H3.18A9.75 9.75 0 0 0 2.25 12c0 1.57.38 3.05.93 4.38l3.34-2.59Z"/><path fill="#EA4335" d="M12 6.18c1.43 0 2.71.49 3.72 1.45l2.79-2.79C16.83 3.27 14.63 2.25 12 2.25a9.75 9.75 0 0 0-8.82 5.37l3.34 2.59C7.29 7.9 9.45 6.18 12 6.18Z"/></svg>; }
function GitHubMark() { return <svg className="githubMark" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 .5C5.73.5.5 5.73.5 12c0 5.02 3.44 9.27 8.21 10.78.6.11.82-.26.82-.58v-2.03c-3.34.73-4.04-1.42-4.04-1.42-.55-1.39-1.34-1.76-1.34-1.76-1.09-.75.08-.74.08-.74 1.21.08 1.84 1.24 1.84 1.24 1.07 1.84 2.81 1.31 3.49 1 .11-.78.42-1.31.76-1.61-2.66-.3-5.46-1.33-5.46-5.92 0-1.31.47-2.38 1.23-3.22-.12-.3-.53-1.52.12-3.17 0 0 1.01-.32 3.3 1.23A11.5 11.5 0 0 1 12 6.76c1.02 0 2.05.14 3.01.41 2.29-1.55 3.3-1.23 3.3-1.23.65 1.65.24 2.87.12 3.17.77.84 1.23 1.91 1.23 3.22 0 4.6-2.8 5.61-5.47 5.91.43.37.81 1.09.81 2.2v3.27c0 .32.22.69.83.57A11.5 11.5 0 0 0 23.5 12C23.5 5.73 18.27.5 12 .5Z"/></svg>; }
function Choice({ label, value, setValue, options }: { label: string; value: string; setValue: (value: string) => void; options: string[][] }) { return <fieldset><legend>{label}</legend><div>{options.map(([id, text]) => <button type="button" className={value === id ? "selected" : ""} aria-pressed={value === id} key={id} onClick={() => setValue(id)}>{value === id ? <Check/> : null}{text}</button>)}</div></fieldset>; }
function RadarIcon() { return <div className="radarIcon"><i/><span/></div>; }
