"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, AtSign, Check, LoaderCircle, LockKeyhole, LogOut, ShieldCheck } from "lucide-react";
import { browserDb } from "@/lib/supabase";
import { isEmailOtp, normalizeEmail, normalizeEmailOtp } from "@/lib/emailOtp";
import { trackProductEvent } from "@/lib/analyticsEvents";

type AccountState = { email: string; token: string; profile: Record<string, unknown> | null };
const googleEnabled = process.env.NEXT_PUBLIC_GOOGLE_AUTH_ENABLED === "true";
export default function AccountPage() {
  const db = useMemo(() => browserDb(), []); const [email, setEmail] = useState(""); const [emailOtp, setEmailOtp] = useState(""); const [emailOtpSent, setEmailOtpSent] = useState(false); const [emailAuthPending, setEmailAuthPending] = useState(false); const [account, setAccount] = useState<AccountState | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const [role, setRole] = useState("developer"); const [ide, setIde] = useState("vscode");
  const destination = typeof window === "undefined" ? "/workspace" : new URLSearchParams(window.location.search).get("next") || "/workspace";
  const entryPoint = destination.startsWith("/monitor") ? "monitor" : destination.startsWith("/extensions/") ? "report" : "account" as const;
  const resumeLabel = entryPoint === "monitor" ? "Continue to monitor this extension." : entryPoint === "report" ? "Continue with this exact public report." : "Continue to your workspace.";
  useEffect(() => { if (!db) { const timer = window.setTimeout(() => setLoading(false), 0); return () => window.clearTimeout(timer); } void db.auth.getSession().then(async ({ data }) => { const session = data.session; if (!session) { setLoading(false); return; } const response = await fetch("/api/profile", { headers: { Authorization: `Bearer ${session.access_token}` } }); const body = await response.json(); setAccount({ email: session.user.email || "", token: session.access_token, profile: body.profile || null }); setLoading(false); }).catch(() => setLoading(false)); }, [db]);
  useEffect(() => { const error = new URLSearchParams(window.location.search).get("error"); const text = error === "invalid_link" ? "That sign-in link is invalid or expired. Start a new sign-in." : error === "missing_code" ? "The sign-in response was incomplete. Start again." : ""; if (!text) return; const timer = window.setTimeout(() => setMessage(text), 0); return () => window.clearTimeout(timer); }, []);
  function callbackUrl() { const destination = new URLSearchParams(window.location.search).get("next") || "/workspace"; const configured = process.env.NEXT_PUBLIC_SITE_URL; const origin = window.location.hostname === "localhost" ? window.location.origin : configured || window.location.origin; return `${origin}/auth/callback?next=${encodeURIComponent(destination)}`; }
  function continueToDestination() { const destination = new URLSearchParams(window.location.search).get("next"); window.location.assign(destination?.startsWith("/") && !destination.startsWith("//") ? destination : "/workspace"); }
  async function oauth() { if (!db) return setMessage("Sign-in is temporarily unavailable. Public extension intelligence remains accessible."); trackProductEvent({ name: "workspace_signup_started", source_route: window.location.pathname, entry_point: entryPoint }); const result = await db.auth.signInWithOAuth({ provider: "google", options: { redirectTo: callbackUrl() } }); if (result.error) setMessage(result.error.message); }
  async function sendEmailOtp() { const address = normalizeEmail(email); if (!db) return setMessage("Supabase Auth is not connected to this deployment."); if (!address) return setMessage("Enter an email address."); trackProductEvent({ name: "workspace_signup_started", source_route: window.location.pathname, entry_point: entryPoint }); setEmailAuthPending(true); const result = await db.auth.signInWithOtp({ email: address, options: { shouldCreateUser: true } }); setEmailAuthPending(false); if (result.error) return setMessage(result.error.message); setEmail(address); setEmailOtp(""); setEmailOtpSent(true); setMessage("Enter the six-digit code we sent to your email."); }
  async function verifyEmailOtp() { const address = normalizeEmail(email); if (!db) return setMessage("Supabase Auth is not connected to this deployment."); if (!isEmailOtp(emailOtp)) return setMessage("Enter the complete six-digit code."); setEmailAuthPending(true); const result = await db.auth.verifyOtp({ email: address, token: emailOtp, type: "email" }); setEmailAuthPending(false); if (result.error) return setMessage("That code is invalid or expired. Request a new one."); continueToDestination(); }
  async function finishOnboarding() { if (!account) return; const response = await fetch("/api/profile", { method: "PATCH", headers: { Authorization: `Bearer ${account.token}`, "Content-Type": "application/json" }, body: JSON.stringify({ role, primary_ide: ide, use_case: "personal" }) }); const body = await response.json(); if (!response.ok) return setMessage(body.error); setAccount({ ...account, profile: body.profile }); continueToDestination(); }
  async function signOut() { await db?.auth.signOut(); setAccount(null); }
  if (loading) return <main className="authProductPage"><div className="authLoading"><LoaderCircle className="spin"/> Opening secure session…</div></main>;
  if (account && !account.profile?.onboarding_completed) return <main className="authProductPage"><section className="onboardingIntro"><span>One-minute setup</span><h1>Make the first decision relevant.</h1><p>GUARDRAILS uses this only to organize your personal workspace and recommended workflows. Scanner results do not change by role.</p></section><section className="onboardingForm"><Choice label="Your role" value={role} setValue={setRole} options={[["developer","Developer"],["security","Security engineer"],["engineering_leader","Engineering leader"]]}/><Choice label="Primary IDE" value={ide} setValue={setIde} options={[["vscode","VS Code"],["cursor","Cursor"],["windsurf","Windsurf"],["vscodium","VSCodium"],["other","Other"]]}/><button className="button buttonDark" onClick={() => void finishOnboarding()}>Open my workspace <ArrowRight/></button>{message ? <p>{message}</p> : null}</section></main>;
  if (account) return <main className="authProductPage"><section className="signedInProduct"><div><span><ShieldCheck/> Signed in</span><h1>Your Monitor workspace.</h1><p>{account.email}</p></div><button className="button buttonQuiet" onClick={() => void signOut()}><LogOut/> Sign out</button></section><section className="accountNextSteps"><Link href="/workspace"><RadarIcon/><div><span>Monitor</span><strong>Open watchlists and release changes</strong><p>Return to decisions that need attention.</p></div><ArrowRight/></Link><Link href="/catalog"><ShieldCheck/><div><span>Explore</span><strong>Find an extension to monitor</strong><p>Start from a published artifact and exact version.</p></div><ArrowRight/></Link></section></main>;
  return <main className="authProductPage"><section className="authValue"><div><span>Free personal workspace</span><h1>Keep watching after the first scan.</h1><p>Save extensions, follow new releases, and preserve the reason behind every install decision.</p><ul><li><Check/> Public catalog and exact-version intelligence</li><li><Check/> Personal extension watchlist</li><li><Check/> Version-change monitoring</li><li><Check/> Personal review history</li></ul></div><aside><LockKeyhole/><strong>Your source code is not part of sign-in.</strong><p>Authentication protects your personal workspace. Public extension analysis remains public.</p></aside></section><section className="oauthPanel"><div><span>Continue to GUARDRAILS</span><h2>{resumeLabel}</h2></div>{googleEnabled?<><button className="oauthButton google" onClick={() => void oauth()}><span className="googleMark" aria-hidden="true">G</span> Continue with Google <ArrowRight/></button><div className="authDivider"><span>or use email</span></div></>:null}<form className="emailOtp" onSubmit={(event) => { event.preventDefault(); void (emailOtpSent ? verifyEmailOtp() : sendEmailOtp()); }}><label><AtSign/><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@company.com" aria-label="Email address" autoComplete="email" spellCheck={false} disabled={emailAuthPending || emailOtpSent} required/></label>{emailOtpSent ? <><input className="emailOtpCode" type="text" inputMode="numeric" pattern="[0-9]{6}" value={emailOtp} onChange={(event) => setEmailOtp(normalizeEmailOtp(event.target.value))} placeholder="6-digit code" aria-label="Six-digit sign-in code" autoComplete="one-time-code" maxLength={6} required/><div className="emailOtpActions"><button type="submit" disabled={emailAuthPending}>{emailAuthPending ? "Verifying…" : "Verify code"}</button><button type="button" className="textAction" onClick={() => void sendEmailOtp()} disabled={emailAuthPending}>Send a new code</button></div></> : <button type="submit" disabled={emailAuthPending}>{emailAuthPending ? "Sending…" : "Email me a code"}</button>}</form>{message ? <p className="authMessage" role="status">{message}</p> : null}<small>By continuing, you agree to use the service responsibly. Public extension intelligence remains available without an account.</small></section></main>;
}
function Choice({ label, value, setValue, options }: { label: string; value: string; setValue: (value: string) => void; options: string[][] }) { return <fieldset><legend>{label}</legend><div>{options.map(([id, text]) => <button type="button" className={value === id ? "selected" : ""} key={id} onClick={() => setValue(id)}>{value === id ? <Check/> : null}{text}</button>)}</div></fieldset>; }
function RadarIcon() { return <div className="radarIcon"><i/><span/></div>; }
