"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, BadgeCheck, Boxes, ChevronRight, CircleCheck, FileCode2, Fingerprint, FolderTree, GitCompareArrows, Network, Package, Radar, ShieldCheck, Terminal, UserRound, Waypoints } from "lucide-react";
import DeepScanButton from "@/app/DeepScanButton";

type RecordValue = Record<string, unknown>;
type Section = "overview" | "alerts" | "capabilities" | "dependencies" | "files" | "versions" | "publisher" | "provenance" | "coverage" | "raw";
type Props = { id: string; version: string; extension: RecordValue; versions: RecordValue[]; scan: RecordValue; findings: RecordValue[]; files: RecordValue[]; dependencies: RecordValue[] };

const sections: Array<{ id: Section; label: string; icon: typeof Radar }> = [
  { id: "overview", label: "Overview", icon: Radar }, { id: "alerts", label: "Alerts", icon: AlertTriangle }, { id: "capabilities", label: "Capabilities", icon: Waypoints }, { id: "dependencies", label: "Dependencies", icon: Package }, { id: "files", label: "Files", icon: FolderTree }, { id: "versions", label: "Versions", icon: GitCompareArrows }, { id: "publisher", label: "Publisher", icon: UserRound }, { id: "provenance", label: "Provenance", icon: Fingerprint }, { id: "coverage", label: "Coverage", icon: ShieldCheck }, { id: "raw", label: "Raw evidence", icon: Terminal },
];

export default function ExtensionDossier({ id, version, extension, versions, scan, findings, files, dependencies }: Props) {
  const [active, setActive] = useState<Section>("overview");
  const severity = normalizedSeverity(String(scan.severity || highestFindingSeverity(findings)));
  const decision = normalizedDecision(String(scan.decision || "incomplete"));
  const capabilities = (scan.capabilities || {}) as Record<string, RecordValue>;
  const grouped = useMemo(() => groupFindings(findings), [findings]);
  const actionableGroups = grouped.filter((group) => group.actionability !== "contextual");
  const contextualGroups = grouped.filter((group) => group.actionability === "contextual");
  const badgeCount = (section: Section) => section === "alerts" ? actionableGroups.length : section === "capabilities" ? Object.keys(capabilities).length : section === "dependencies" ? dependencies.length : section === "files" ? files.length : section === "versions" ? versions.length : 0;
  return <main className="dossierPage">
    <header className="dossierMast">
      <div className="dossierIdentity"><ArtifactIcon url={String(extension.icon_url || "")} publisher={String(extension.publisher || "")}/><div><span>Exact artifact intelligence</span><h1>{String(extension.display_name || id)}</h1><code>{id}@{version}</code></div></div>
      <div className={`dossierDecision ${decision}`}><span>Install recommendation</span><strong>{decisionLabel(decision)}</strong><p>{String(scan.decision_reason || decisionExplanation(decision))}</p><DeepScanButton extensionId={id} version={version}/></div>
    </header>
    <div className="dossierMeta"><span>{String(extension.publisher || "Not reported")}</span><span>{String(extension.registry || "Registry not reported")}</span><span>Scanned {formatDate(String(scan.scanned_at || ""))}</span><span>Artifact <code>{String(scan.artifact_sha256 || "unavailable").slice(0, 16)}</code></span></div>
    <div className="dossierLayout">
      <aside className="dossierRail" aria-label="Extension intelligence sections"><strong>Extension intelligence</strong>{sections.map(({ id: section, label, icon: Icon }) => <button key={section} type="button" className={active === section ? "active" : ""} onClick={() => setActive(section)} title={label}><Icon/><span>{label}</span>{badgeCount(section) ? <b>{badgeCount(section)}</b> : null}</button>)}</aside>
      <section className="dossierContent" aria-live="polite">{active === "overview" ? <Overview decision={decision} severity={severity} scan={scan} actionableGroups={actionableGroups} contextualGroups={contextualGroups} capabilities={capabilities} files={files} onOpenAlerts={() => setActive("alerts")}/> : null}{active === "alerts" ? <Alerts actionableGroups={actionableGroups} contextualGroups={contextualGroups}/> : null}{active === "capabilities" ? <Capabilities capabilities={capabilities}/> : null}{active === "dependencies" ? <Dependencies dependencies={dependencies}/> : null}{active === "files" ? <Files files={files}/> : null}{active === "versions" ? <Versions versions={versions} current={version}/> : null}{active === "publisher" ? <Publisher extension={extension} files={files}/> : null}{active === "provenance" ? <Provenance scan={scan}/> : null}{active === "coverage" ? <Coverage scan={scan}/> : null}{active === "raw" ? <Raw scan={scan} findings={findings}/> : null}</section>
    </div>
  </main>;
}

function Overview({ decision, severity, scan, actionableGroups, contextualGroups, capabilities, files, onOpenAlerts }: { decision: string; severity: string; scan: RecordValue; actionableGroups: Group[]; contextualGroups: Group[]; capabilities: Record<string, RecordValue>; files: RecordValue[]; onOpenAlerts: () => void }) { return <><SectionHead eyebrow="Security brief" title={decisionHeadline(decision)} detail={decision === "allow" ? "Required analysis completed without evidence that crosses the active review policy." : "Open the decision-relevant behavior groups, then compare them with the extension’s documented purpose."}/><div className="briefScores"><Score value={Number(scan.malware_score || 0)} label="Malware evidence" tone="danger"/><Score value={Number(scan.risk_score || 0)} label="Operational risk" tone="warning"/><Score value={Number(scan.coverage_percent || 0)} label="Analysis coverage" tone="confidence"/></div><div className="overviewGrid"><article className="whyCard"><span>Evidence summary</span><h3>{actionableGroups.length ? `${actionableGroups.length} behavior group${actionableGroups.length === 1 ? "" : "s"} requires${actionableGroups.length === 1 ? "" : ""} context.` : "No behavior group requires review."}</h3><p>{actionableGroups[0]?.summary || "Contextual capabilities remain available separately and do not change this decision."}</p><div><b>{contextualGroups.length}</b><span>context groups</span><b>{Object.keys(capabilities).length}</b><span>capability families</span></div></article><article className="identityCard"><Fingerprint/><span>Artifact identity</span><code>{String(scan.artifact_sha256 || "unavailable")}</code><p>Build {String(scan.scanner_build || "not recorded").slice(0, 12)} · ruleset {String(scan.ruleset_version || "not recorded")}</p></article></div><section className="evidencePreview"><div><span>Decision-relevant evidence</span><button type="button" onClick={onOpenAlerts}>Open evidence <ChevronRight/></button></div>{actionableGroups.slice(0, 3).map((group) => <article key={group.rule}><Severity severity={group.severity}/><div><strong>{group.summary}</strong><p>{group.count} observed location{group.count === 1 ? "" : "s"} · {actionabilityLabel(group.actionability)}</p></div></article>)}</section></> }
function Alerts({ actionableGroups, contextualGroups }: { actionableGroups: Group[]; contextualGroups: Group[] }) { return <><SectionHead eyebrow="Evidence" title="Evidence, grouped by behavior" detail="Repeated locations are one behavior group. Expand a group to inspect every recorded location and evidence class."/>{actionableGroups.length ? <div className="dossierRows">{actionableGroups.map((group) => <EvidenceGroup key={group.rule} group={group} open/>)}</div> : <Empty text="No behavior group requires review under the completed policy."/>}{contextualGroups.length ? <details className="contextEvidence"><summary>{contextualGroups.length} contextual behavior group{contextualGroups.length === 1 ? "" : "s"} — not standalone malware evidence</summary><div className="dossierRows">{contextualGroups.map((group) => <EvidenceGroup key={group.rule} group={group}/>)}</div></details> : null}</> }
function EvidenceGroup({ group, open = false }: { group: Group; open?: boolean }) { return <details open={open}><summary><Severity severity={group.severity}/><div><strong>{group.summary}</strong><code>{group.rule}</code><p>{actionabilityLabel(group.actionability)} · {group.evidenceClasses.join(", ")} evidence</p></div></summary><div className="evidenceLocations"><p>{group.count} observation{group.count === 1 ? "" : "s"}. Every recorded location is listed below.</p>{group.locations.length ? group.locations.map((location) => <code key={location}>{location}</code>) : <small>No file location was recorded.</small>}</div></details> }
function Capabilities({ capabilities }: { capabilities: Record<string, RecordValue> }) { const entries = Object.entries(capabilities); return <><SectionHead eyebrow="Capability map" title="What this extension can access" detail="Capabilities describe power, not malicious intent. Compare each one to the extension's stated purpose."/>{entries.length ? <div className="dossierCapabilityGrid">{entries.map(([key, value]) => <article key={key}>{capabilityIcon(key)}<div><strong>{key.replaceAll("_", " ")}</strong><p>{Array.isArray(value.evidence) ? `${value.evidence.length} evidence location(s)` : "Declared or detected capability"}</p></div></article>)}</div> : <Empty text="No capability families were recorded by this scan."/>}</> }
function Dependencies({ dependencies }: { dependencies: RecordValue[] }) { return <><SectionHead eyebrow="Supply chain" title="Runtime dependencies" detail="Packages are tied to this exact artifact, not to the repository in general."/>{dependencies.length ? <div className="dossierTable"><div><span>Package</span><span>Version</span><span>Relationship</span><span>Advisories</span></div>{dependencies.map((item) => <article key={`${item.name}@${item.version}`}><strong>{String(item.name)}</strong><code>{String(item.version)}</code><span>{String(item.relationship || "runtime")}</span><span>{Array.isArray(item.advisories) ? item.advisories.length : 0}</span></article>)}</div> : <Empty text="No runtime dependencies were reported for this artifact."/>}</> }
function Files({ files }: { files: RecordValue[] }) { return <><SectionHead eyebrow="Artifact explorer" title="Files inside the published package" detail="File names, sizes, and hashes are taken from the exact artifact. Code was not executed."/>{files.length ? <div className="dossierFiles"><div><span>/</span><span>{files.length} files</span></div>{files.slice(0, 500).map((item) => <article key={String(item.path)}><FileCode2/><code>{String(item.path)}</code><span>{formatBytes(Number(item.size_bytes || 0))}</span><small>{String(item.sha256 || "").slice(0, 12)}</small></article>)}</div> : <Empty text="The file inventory was not emitted by this scan."/>}</> }
function Versions({ versions, current }: { versions: RecordValue[]; current: string }) { return <><SectionHead eyebrow="Release history" title="Published versions" detail="Severity is recorded per immutable version and exact artifact hash."/><div className="dossierTable versionTable"><div><span>Version</span><span>Published</span><span>Severity</span><span/></div>{versions.map((item) => { const severity = normalizedSeverity(String(item.severity || "INFO")); return <article key={String(item.version)} className={String(item.version) === current ? "current" : ""}><strong>{String(item.version)}</strong><span>{formatDate(String(item.published_at || ""))}</span><Severity severity={severity}/><span>{String(item.version) === current ? "Current" : "Recorded"}</span></article>; })}</div></> }
function Publisher({ extension, files }: { extension: RecordValue; files: RecordValue[] }) { const readme = files.find((item) => /(^|\/)readme(?:\.[a-z]+)?$/i.test(String(item.path || ""))); return <><SectionHead eyebrow="Package information" title="Publisher and package context" detail="Identity and popularity establish context. They do not override artifact evidence."/><div className="publisherGrid"><article><UserRound/><span>Publisher</span><strong>{String(extension.publisher || "Not reported")}</strong><p>{extension.publisher_verified ? "Registry reports a verified publisher." : "Registry does not report publisher verification."}</p></article><article><Package/><span>Package</span><strong>{String(extension.id || "Not reported")}</strong><p>{String(extension.registry || "Registry not reported")}</p></article><article><BadgeCheck/><span>Marketplace context</span><strong>{Number(extension.installs || 0).toLocaleString()} installs</strong><p>Rating {String(extension.rating || "not reported")}</p></article><article><FileCode2/><span>Documentation</span><strong>{readme ? "README packaged" : "README not packaged"}</strong><p>{String(extension.description || "No Marketplace description was reported.")}</p></article></div></> }
function Provenance({ scan }: { scan: RecordValue }) { return <><SectionHead eyebrow="Provenance" title="Exact artifact identity" detail="This is the evidence boundary for the report. A publisher name or repository cannot substitute for it."/><div className="provenanceList"><Fact label="Artifact SHA-256" value={String(scan.artifact_sha256 || "Not recorded")}/><Fact label="Scanner build" value={String(scan.scanner_build || "Not recorded")}/><Fact label="Ruleset" value={String(scan.ruleset_version || "Not recorded")}/><Fact label="Scanner profile" value={String(scan.profile || "deep")}/><Fact label="Scan time" value={formatDate(String(scan.scanned_at || ""))}/><Fact label="VSIX signature" value={String((scan.artifacts as RecordValue | undefined)?.vsix_signature ? "Recorded in artifact evidence" : "Not reported")}/></div></> }
function Coverage({ scan }: { scan: RecordValue }) { const providers = (scan.provider_coverage || {}) as Record<string, RecordValue>; const coverage = (scan.analysis_coverage || {}) as RecordValue; return <><SectionHead eyebrow="Analysis boundary" title="What was actually assessed" detail="Coverage explains the scope of the evidence. It is not a safety guarantee."/><div className="coverageGrid"><Fact label="Analysis coverage" value={`${Number(scan.coverage_percent || 0)}%`}/><Fact label="Declared entrypoints" value={String(arrayLength(coverage.declared_entrypoints))}/><Fact label="Resolved entrypoints" value={String(arrayLength(coverage.resolved_entrypoints))}/><Fact label="Executable candidates" value={String(arrayLength(coverage.executable_candidates))}/></div><div className="providerGrid">{Object.entries(providers).map(([name, value]) => <article key={name}><span>{name.replaceAll("_", " ")}</span><strong>{String(value.status || "not assessed")}</strong><p>{Number(value.finding_count || 0)} normalized findings</p></article>)}</div></> }
function Raw({ scan, findings }: { scan: RecordValue; findings: RecordValue[] }) { return <><SectionHead eyebrow="Technical evidence" title="Raw scanner fields" detail="Manifests, hashes, and normalized JSON are available here so they do not compete with the decision summary."/><pre className="rawEvidence">{JSON.stringify({ scan, findings }, null, 2)}</pre></> }
function SectionHead({ eyebrow, title, detail }: { eyebrow: string; title: string; detail: string }) { return <header className="dossierHead"><span>{eyebrow}</span><h2>{title}</h2><p>{detail}</p></header> }
function Score({ value, label, tone }: { value: number; label: string; tone: string }) { return <article className={`briefScore ${tone}`}><div><strong>{Math.max(0, Math.min(100, value))}</strong><span>/100</span></div><p>{label}</p></article> }
function Severity({ severity }: { severity: string }) { return <b className={`severity ${severity.toLowerCase()}`}>{displaySeverity(severity)}</b> }
function Fact({ label, value }: { label: string; value: string }) { return <article><span>{label}</span><strong>{value}</strong></article> }
function Empty({ text }: { text: string }) { return <div className="dossierEmpty"><CircleCheck/><p>{text}</p></div> }
function ArtifactIcon({ url, publisher }: { url: string; publisher: string }) { return <span className="dossierIcon">{publisher.slice(0, 2).toUpperCase()}{url ? <img src={url} alt="" onError={(event) => event.currentTarget.remove()}/> : null}</span> }
type Group = { rule: string; summary: string; severity: string; count: number; locations: string[]; actionability: string; evidenceClasses: string[] };
function groupFindings(findings: RecordValue[]): Group[] { const groups = new Map<string, Group>(); for (const item of findings) { const rule = String(item.rule_id || "observed-capability"); const current = groups.get(rule); const findingSeverity = normalizedSeverity(String(item.severity || "INFO")); const actionability = String(item.actionability || "contextual"); const evidenceClass = String(item.evidence_class || (item.evidence as RecordValue | undefined)?.evidence_class || "weak"); const locations = Array.isArray(item.file_refs) ? item.file_refs.map(String) : []; if (current) { current.count += 1; current.severity = severityRank(findingSeverity) > severityRank(current.severity) ? findingSeverity : current.severity; current.actionability = actionabilityRank(actionability) > actionabilityRank(current.actionability) ? actionability : current.actionability; for (const location of locations) if (!current.locations.includes(location)) current.locations.push(location); if (!current.evidenceClasses.includes(evidenceClass)) current.evidenceClasses.push(evidenceClass); } else groups.set(rule, { rule, summary: String(item.summary || item.evidence_summary || rule.replaceAll("-", " ")), severity: findingSeverity, count: 1, locations, actionability, evidenceClasses: [evidenceClass] }); } return [...groups.values()].sort((a, b) => actionabilityRank(b.actionability) - actionabilityRank(a.actionability) || severityRank(b.severity) - severityRank(a.severity) || b.count - a.count); }
function normalizedSeverity(value: string) { return ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"].includes(value.toUpperCase()) ? value.toUpperCase() : "INFO"; }
function displaySeverity(value: string) { return value === "INFO" ? "INFORMATIONAL" : value; }
function severityRank(value: string) { return ({ CRITICAL: 5, HIGH: 4, MEDIUM: 3, LOW: 2, INFO: 1 } as Record<string, number>)[value] || 0; }
function highestFindingSeverity(findings: RecordValue[]) { return findings.reduce((highest, item) => severityRank(normalizedSeverity(String(item.severity || "INFO"))) > severityRank(highest) ? normalizedSeverity(String(item.severity || "INFO")) : highest, "INFO"); }
function normalizedDecision(value: string) { return ["allow", "review", "block", "incomplete"].includes(value) ? value : "incomplete"; }
function decisionLabel(value: string) { return value === "allow" ? "No Review Required" : value === "review" ? "Review Before Install" : value === "block" ? "Do Not Install" : "Analysis Incomplete"; }
function decisionExplanation(value: string) { return value === "allow" ? "Required analysis completed without evidence that crosses the review policy." : value === "review" ? "Review the cited behavior before approving this exact artifact." : value === "block" ? "The scanner found evidence that requires this exact artifact to be rejected." : "Required analysis did not complete; this artifact cannot be approved yet."; }
function decisionHeadline(value: string) { return value === "allow" ? "No evidence currently requires review." : value === "review" ? "Review decision-relevant behavior before installation." : value === "block" ? "This exact artifact should not be installed." : "Analysis must complete before an approval decision."; }
function actionabilityRank(value: string) { return ({ block: 4, investigate: 3, review: 2, contextual: 1 } as Record<string, number>)[value] || 1; }
function actionabilityLabel(value: string) { return value === "block" ? "block evidence" : value === "investigate" ? "investigation evidence" : value === "review" ? "review evidence" : "contextual observation"; }
function capabilityIcon(key: string) { if (key.includes("network")) return <Network/>; if (key.includes("shell") || key.includes("process")) return <Terminal/>; if (key.includes("dependency")) return <Package/>; return <Boxes/>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "Not recorded" : new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(date); }
function formatBytes(value: number) { return value < 1024 ? `${value} B` : value < 1024 ** 2 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1024 ** 2).toFixed(1)} MB`; }
function arrayLength(value: unknown) { return Array.isArray(value) ? value.length : 0; }
