export type MetricDomain = { id: string; label: string; short: string; detail: string; why: string; outputs: string[] };

export const metricCatalog: MetricDomain[] = [
  { id: "confirmed-intelligence", label: "Confirmed intelligence", short: "Known-bad artifacts and malicious dependencies.", detail: "Exact package and file SHA-256 matches, configured threat intelligence, and dependencies identified as malicious.", why: "This is authoritative evidence and can directly drive a BLOCK decision when the intelligence source and artifact identity are valid.", outputs: ["artifact SHA-256", "feed source", "matched dependency"] },
  { id: "behavior-chains", label: "Behavior chains", short: "Sources connected to security-sensitive sinks.", detail: "Workspace input, webview messages, decoded payloads, credential surfaces, downloads, process execution, filesystem access, and outbound network transfer.", why: "Correlation is stronger than counting isolated API names. A source-to-sink path explains how a capability could become abuse.", outputs: ["source", "sink", "file and line", "correlation rule"] },
  { id: "code-evasion", label: "Code and evasion", short: "Dynamic calls, constructed arguments, and hidden content.", detail: "AST-resolved bracket notation, computed call targets, encoded dynamic execution, invisible Unicode controls, obfuscation, and dynamic code loading.", why: "Attackers can evade plain-text matching. Structural parsing and signatures recover signals that regex alone misses.", outputs: ["AST node", "resolved value", "YARA match", "code location"] },
  { id: "capability-surface", label: "Capability surface", short: "What extension code is able to reach.", detail: "Process execution, shell invocation, network and filesystem access, install scripts, agent tooling, native code, and packed artifacts.", why: "Capability is not proof of intent, but it defines blast radius and tells reviewers where explicit user intent and isolation are required.", outputs: ["capability", "activation context", "entrypoint", "review guidance"] },
  { id: "credential-exposure", label: "Credential and data exposure", short: "Secret capture, storage, control, and transfer paths.", detail: "Credential prompts and configuration keys, extension state storage, command surfaces, clipboard access, and flows into files, processes, or networks.", why: "IDE extensions share a privileged user environment. Insecure storage and cross-extension control can expose secrets even without malware.", outputs: ["secret source", "storage surface", "control surface", "transfer sink"] },
  { id: "dependencies", label: "Dependency security", short: "Malicious or vulnerable runtime packages.", detail: "Runtime dependency inventory is checked against configured vulnerability and malicious-package intelligence.", why: "A clean extension entrypoint can still inherit exploitable or malicious behavior through its dependency graph.", outputs: ["package", "version", "advisory", "fix version"] },
  { id: "artifact-provenance", label: "Artifact and provenance", short: "The exact bytes, packaging, and marketplace history.", detail: "Package and file hashes, native and packed payloads, embedded PE content, and marketplace removal signals.", why: "A name or repository is not the artifact. Exact hashes and packaging evidence make a decision reproducible across machines and releases.", outputs: ["package hash", "file hashes", "artifact type", "marketplace signal"] },
  { id: "agentic", label: "AI, agent, and MCP", short: "Tools that let models act inside the IDE.", detail: "Language-model tools, chat participants, MCP server surfaces, agent data access, and network or execution combinations.", why: "Agent tools turn prompts into actions. Their approval, filesystem, terminal, and network boundaries need explicit review.", outputs: ["tool contribution", "MCP surface", "data access", "action sink"] },
  { id: "webview", label: "Webview boundaries", short: "Browser-like messages entering extension privileges.", detail: "Message events from webviews are traced toward process execution and other privileged extension APIs.", why: "A webview is a lower-trust input boundary; schema validation and narrow message handlers are essential.", outputs: ["message source", "handler", "execution sink", "location"] },
  { id: "client-posture", label: "IDE client posture", short: "Whether local settings weaken IDE guardrails.", detail: "Workspace Trust, broad trusted paths, automatic tasks, agent auto-approval, terminal and URL approval rules, and untrusted-workspace overrides.", why: "Extension findings answer what a package can do. Posture metrics answer whether local policy makes that behavior easier to trigger.", outputs: ["control status", "0-100 posture pressure", "client", "remediation"] },
  { id: "analysis-coverage", label: "Analysis coverage", short: "What was inspected, skipped, or unsupported.", detail: "Declared and discovered entrypoints, files inspected, provider availability, parse failures, truncation, archive limits, and unsupported native code.", why: "No findings is meaningful only when coverage is complete. Missing mandatory analysis produces INCOMPLETE, not ALLOW.", outputs: ["entrypoint coverage", "provider status", "skipped files", "completion state"] },
  { id: "release-change", label: "Release change", short: "What changed since the trusted baseline.", detail: "Decisions, findings, capabilities, dependencies, entrypoints, file hashes, and package identity are compared between versions.", why: "Trust is version-specific. A low-risk update can add one new execution path or replace a binary without changing the product name.", outputs: ["new findings", "removed findings", "capability delta", "hash delta"] }
];

export const evidenceClasses = [
  ["confirmed", "Authoritative artifact or package intelligence. May directly drive BLOCK."],
  ["correlated", "Multiple related signals or a source-to-sink path. Usually drives REVIEW and may block under strict policy."],
  ["observed", "Behavior recorded by an external controlled analysis provider. Not produced by the hosted static path."],
  ["dependency", "Known vulnerability or package intelligence attached to a resolved runtime dependency."],
  ["provenance", "Artifact, marketplace, repository, or release-origin evidence."],
  ["capability", "A sensitive power or structural behavior that requires context and user-intent review."],
  ["exposure", "A secret storage, input, command, or cross-extension boundary that may weaken isolation."],
  ["weak", "A single common static indicator. Context only; never sufficient for a malware claim by itself."]
];
