export type ResearchArticle = { slug: string; category: string; title: string; summary: string; published: string; reading: string; sections: Array<{ heading: string; paragraphs: string[] }>; sources?: Array<{ label: string; href: string }> };
export const researchArticles: ResearchArticle[] = [
  { slug: "solidity-pro", category: "Case study", title: "Solidity Pro: the wallet stealer behind the audit tool", summary: "GuardRails flagged credential harvesting, heavy obfuscation, and unattended remote extension updates in Solidity Pro—the same behavior documented in public reporting on the campaign.", published: "28 August 2026", reading: "5 min", sections: [
    { heading: "The cover story", paragraphs: ["Solidity Pro presented itself as an AI-powered smart-contract auditor, gas optimiser, and developer utility. The public v3.4.0 source release carries the same familiar signals: a polished developer-tooling pitch, startup activation, and a bundle that makes the important behaviour difficult to inspect at a glance.", "Public threat research identified Solidity Pro packages from the helper-beeps and web3devtoolsx publishers as part of a credential-stealing campaign targeting Web3 developers. GuardRails did not discover the campaign; this case study documents what the scanner independently flagged in the public source release."] },
    { heading: "What GuardRails flagged", paragraphs: ["GuardRails produced a BLOCK decision from correlated static evidence, not from a single suspicious API. The source includes a Web3Analytics module that searches for wallet data, cloud credentials, developer tokens, SSH material, and configuration files; it then combines those collection paths with network delivery behaviour.", "The compiled extension bundle is heavily obfuscated. GuardRails also found an unattended remote-VSIX update chain: code that can download an extension package, write it locally, and hand it to the editor for installation without a visible integrity boundary. Those three signals together form a credible abuse path."] },
    { heading: "Why this deserved a block", paragraphs: ["Developer tools do need filesystem and network access. That alone is not the story. This release combined targeted secret collection, outbound delivery, obfuscation, and a remote update mechanism in a tool marketed for Solidity development. The result is an installation path with an unacceptable blast radius for a developer workstation.", "The scanner’s job is to make that decision explainable: show the behavior, the affected files, and the rule correlation. A score can help order work; it cannot replace the reason for the decision."] },
    { heading: "Technical notes", paragraphs: ["This analysis used the public web3devtoolsx/solidity-pro Git source release whose manifest identifies version 3.4.0. The original marketplace artifact was removed before this validation and is not represented as a hash-verified VSIX here.", "The campaign facts and historical version context are attributed to the public research below. GuardRails’ conclusion on this page is limited to the static behaviour found in the analyzed public source release."] },
  ], sources: [
    { label: "Yeeth Security: Solidity Pro’s WhiteCobra Chassis", href: "https://yeethsecurity.com/blog/2026-08-06-Solidity-Pro-WhiteCobra-C2-to-Telegram" },
    { label: "Public Solidity Pro v3.4.0 source release", href: "https://github.com/web3devtoolsx/solidity-pro/tree/fe794a2bdad03acf5e808eb7c8f36cfc62b8a64b" },
  ] },
  { slug: "capability-is-not-malware", category: "Methodology", title: "Capability is not malware", summary: "Why shell, network, filesystem, and credential access need intent and correlation before they become a security conclusion.", published: "12 July 2026", reading: "6 min", sections: [
    { heading: "Power is part of the product", paragraphs: ["Language servers launch processes. Cloud extensions make network requests. Formatters read and write files. These behaviors define useful developer tooling, but they also define the extension's blast radius.", "A scanner that labels every privileged API as malicious produces noise. A scanner that ignores those APIs cannot explain what the extension could do after installation."] },
    { heading: "The evidence ladder", paragraphs: ["GUARDRAILS records an isolated capability as context. Evidence becomes actionable when it adds untrusted input, a sensitive sink, lifecycle execution, evasion, an unexpected destination, or authoritative malicious intelligence.", "This distinction is why REVIEW exists separately from BLOCK. Review asks whether behavior matches publisher intent. Block says the exact artifact crossed a policy boundary."] },
    { heading: "What reviewers should demand", paragraphs: ["The finding must identify the exact artifact, version, file, rule, evidence class, and expected verification step. Reputation can add context, but it cannot erase executable evidence or prove that future releases are safe."] },
  ]},
  { slug: "artifact-is-the-boundary", category: "Supply chain", title: "The extension artifact is the boundary", summary: "A repository, publisher name, and download count cannot substitute for the exact bytes installed in the IDE.", published: "12 July 2026", reading: "5 min", sections: [
    { heading: "Names are mutable; hashes are not", paragraphs: ["Users install a VSIX, not a GitHub repository. Build output, vendored dependencies, generated bundles, native binaries, and packed resources can differ materially from the source people review.", "Every GUARDRAILS decision therefore binds to publisher.extension, version, registry source, and artifact SHA-256."] },
    { heading: "Why versions matter", paragraphs: ["A trusted extension can publish a compromised update. A legitimate feature can introduce a new process or credential boundary. Version comparison makes new access visible without treating every update as malicious."] },
    { heading: "Reproducible evidence", paragraphs: ["File hashes, resolved entrypoints, dependency versions, analyzer rulesets, and coverage limitations make the decision reproducible. If the artifact or ruleset changes, the old conclusion is historical evidence rather than current approval."] },
  ]},
  { slug: "reading-a-decision", category: "Field guide", title: "Reading an IDE extension decision", summary: "A practical guide to ALLOW, REVIEW, BLOCK, and INCOMPLETE without mistaking scores for certainty.", published: "12 July 2026", reading: "7 min", sections: [
    { heading: "Start with the operational decision", paragraphs: ["ALLOW means required analysis completed without crossing the active review or block policy. REVIEW means sensitive or correlated behavior needs human context. BLOCK means authoritative or policy-rejected evidence applies. INCOMPLETE means analysis coverage cannot support approval."] },
    { heading: "Then inspect the reason", paragraphs: ["The bottom line should state what the extension can do, why that access surfaced, and what must be verified before installation. Counts and severity labels are supporting evidence, not the explanation."] },
    { heading: "Scores order work", paragraphs: ["Risk and malware indexes prioritize evidence; they are not calibrated probabilities. Security dimensions show where deductions came from, while analysis confidence shows whether required entrypoints and providers completed."] },
    { heading: "Approval expires with the artifact", paragraphs: ["An approval belongs to one hash and ruleset. New versions should be compared for capabilities, dependencies, findings, entrypoints, files, and artifact identity before the decision is carried forward."] },
  ]},
];
export function getResearch(slug: string) { return researchArticles.find((article) => article.slug === slug); }
