export type ResearchArticle = { slug: string; category: string; title: string; summary: string; published: string; reading: string; sections: Array<{ heading: string; paragraphs: string[] }> };
export const researchArticles: ResearchArticle[] = [
  { slug: "capability-is-not-malware", category: "Methodology", title: "Capability is not malware", summary: "Why shell, network, filesystem, and credential access need intent and correlation before they become a security conclusion.", published: "12 July 2026", reading: "6 min", sections: [
    { heading: "Power is part of the product", paragraphs: ["Language servers launch processes. Cloud extensions make network requests. Formatters read and write files. These behaviors define useful developer tooling, but they also define the extension's blast radius.", "A scanner that labels every privileged API as malicious produces noise. A scanner that ignores those APIs cannot explain what the extension could do after installation."] },
    { heading: "The evidence ladder", paragraphs: ["GUARDRAILS records an isolated capability as context. Evidence becomes actionable when it adds untrusted input, a sensitive sink, lifecycle execution, evasion, an unexpected destination, or authoritative malicious intelligence.", "This distinction is why REVIEW exists separately from BLOCK. Review asks whether behavior matches publisher intent. Block says the exact artifact crossed a policy boundary."] },
    { heading: "What reviewers should demand", paragraphs: ["The finding must identify the exact artifact, version, file, rule, evidence class, and expected verification step. Reputation can add context, but it cannot erase executable evidence or prove that future releases are safe."] },
  ]},
  { slug: "artifact-is-the-boundary", category: "Supply chain", title: "The extension artifact is the boundary", summary: "A repository, publisher name, and download count cannot substitute for the exact bytes installed in the IDE.", published: "12 July 2026", reading: "5 min", sections: [
    { heading: "Names are mutable; hashes are not", paragraphs: ["Users install a VSIX, not a GitHub repository. Build output, vendored dependencies, generated bundles, native binaries, and packed resources can differ materially from the source people review.", "Every GUARDRAILS decision therefore binds to publisher.extension, version, registry source, and artifact SHA-256."] },
    { heading: "Why versions matter", paragraphs: ["A trusted extension can publish a compromised update. A legitimate feature can introduce a new process or credential boundary. Version comparison makes new access visible without treating every update as malicious."] },
    { heading: "Reproducible evidence", paragraphs: ["File hashes, resolved entrypoints, dependency versions, analyzer rulesets, and coverage limitations make the decision reproducible. If the artifact or ruleset changes, the old conclusion is historical evidence rather than current approval."] },
  ]},
  { slug: "reading-a-decision", category: "Field guide", title: "Reading an IDE extension decision", summary: "A practical guide to ALLOW, REVIEW, BLOCK, and INCOMPLETE without mistaking scores for certainty.", published: "12 July 2026", reading: "7 min", sections: [
    { heading: "Start with the operational decision", paragraphs: ["ALLOW means required analysis completed without crossing the active review or block policy. REVIEW means sensitive or correlated behavior needs human context. BLOCK means authoritative or policy-rejected evidence applies. INCOMPLETE means analysis coverage cannot support approval."] },
    { heading: "Then inspect the reason", paragraphs: ["The bottom line should state what the extension can do, why that access surfaced, and what must be verified before installation. Counts and severity labels are supporting evidence, not the explanation."] },
    { heading: "Scores order work", paragraphs: ["Risk and malware indexes prioritize evidence; they are not calibrated probabilities. Security dimensions show where deductions came from, while analysis confidence shows whether required entrypoints and providers completed."] },
    { heading: "Approval expires with the artifact", paragraphs: ["An approval belongs to one hash and ruleset. New versions should be compared for capabilities, dependencies, findings, entrypoints, files, and artifact identity before the decision is carried forward."] },
  ]},
];
export function getResearch(slug: string) { return researchArticles.find((article) => article.slug === slug); }
