export default function SettingsPage() {
  return <main className="shell architecturePage">
    <section className="pageHero"><div><p className="eyebrow">Trust architecture</p><h1>Where analysis runs and what leaves the machine.</h1><p className="heroCopy">Published extensions and local installations have different trust boundaries. IDE Scanner keeps those workflows explicit.</p></div></section>
    <section className="architectureBands"><article><span>Public catalog</span><h2>Registry artifact → isolated public runner</h2><p>GitHub Actions downloads one exact published VSIX, installs the canonical analyzers, records the result, then discards the runner. Extension code is never executed.</p><div><code>Native static</code><code>JavaScript AST</code><code>Semgrep</code><code>YARA</code><code>OSV</code></div></article><article><span>Local inventory</span><h2>User machine → local scanner</h2><p>Installed extensions cannot be read by a website. The local CLI scans them on the machine and uploads only the canonical report when the user explicitly chooses the agent workflow.</p><div><code>ide-scanner agent --all</code></div></article><article><span>Persistent intelligence</span><h2>Signed result → Supabase</h2><p>Vercel accepts HMAC-signed schema 2.2 results. Public artifact evidence is readable; account, watchlist and team workflow data is protected by row-level security.</p><div><code>Postgres</code><code>Supabase Auth</code><code>RLS</code></div></article></section>
    <section className="architectureRules"><div><p className="eyebrow">Non-negotiable boundaries</p><h2>What the product refuses to blur</h2></div><div><article><strong>Quick is not Deep</strong><p>Hosted static analysis never claims missing analyzers ran.</p></article><article><strong>Identity is not safety</strong><p>Publisher verification and popularity cannot override artifact evidence.</p></article><article><strong>Capability is not malware</strong><p>Powerful APIs remain contextual until behavior or intelligence strengthens the evidence.</p></article><article><strong>Incomplete is not allow</strong><p>A required provider failure prevents a complete approval decision.</p></article></div></section>
    <section className="twoColumnDocs"><div><h2>Hosted environment</h2><Env name="NEXT_PUBLIC_SUPABASE_URL" detail="Public Supabase project URL."/><Env name="NEXT_PUBLIC_SUPABASE_ANON_KEY" detail="RLS-bound browser key."/><Env name="SUPABASE_SERVICE_ROLE_KEY" detail="Server-only result ingestion key."/><Env name="GITHUB_ACTIONS_TOKEN" detail="Fine-grained scanner workflow dispatch token."/><Env name="SCAN_CALLBACK_SECRET" detail="Shared HMAC callback secret."/></div><div><h2>Public interfaces</h2><Env name="/api/catalog" detail="Searches persistent top-250 intelligence with registry fallback."/><Env name="/api/deep-scans" detail="Deduplicates and queues exact-version analysis."/><Env name="/api/internal/scan-results" detail="Validates and ingests signed canonical bundles."/><Env name="/api/teams" detail="Authenticated watchlist and review workflow."/></div></section>
  </main>;
}
function Env({ name, detail }: { name: string; detail: string }) { return <div className="architectureDetail"><code>{name}</code><p>{detail}</p></div>; }
