import Link from "next/link";
import { notFound } from "next/navigation";
import IntelligenceScores from "@/app/IntelligenceScores";
import { AlertTriangle, Box, ChevronRight, CircleCheck, FileCode2, GitCompareArrows, Network, Package, ShieldCheck, Terminal } from "lucide-react";
import { getExtensionProduct, getVersionProduct } from "@/lib/productData";
import DeepScanButton from "@/app/DeepScanButton";

export const dynamic = "force-dynamic";
export default async function VersionPage({ params }: { params: Promise<{ id: string; version: string }> }) {
  const route = await params; const id = decodeURIComponent(route.id); const version = decodeURIComponent(route.version);
  const [extension, product] = await Promise.all([getExtensionProduct(id), getVersionProduct(id, version)]);
  if (!extension) notFound();
  const scan = product?.scan as Record<string, unknown> | null | undefined;
  const findings = (product?.findings || []) as Array<Record<string, unknown>>;
  const files = (product?.files || []) as Array<Record<string, unknown>>;
  const dependencies = (product?.dependencies || []) as Array<Record<string, unknown>>;
  if (!scan) return <main className="versionProductPage"><VersionCrumb id={id} name={extension.extension.display_name} version={version}/><section className="emptyVersion"><Box size={34}/><span>Exact release</span><h1>{extension.extension.display_name} <code>@{version}</code></h1><p>This version is published, but no completed Deep Scan exists. Registry metadata alone cannot establish behavior, dependency health or artifact integrity.</p><DeepScanButton extensionId={id} version={version}/></section></main>;
  const dimensions = (scan.security_dimensions || {}) as Record<string, { score?: number; status?: string; deductions?: unknown[] }>;
  const capabilities = (scan.capabilities || {}) as Record<string, Record<string, unknown>>;
  const decision = String(scan.decision || "incomplete");
  return <main className="versionProductPage">
    <VersionCrumb id={id} name={extension.extension.display_name} version={version}/>
    <section className="versionMast"><div><span className="scanProfile">Deep Scan · exact artifact</span><h1>{extension.extension.display_name}</h1><code>{id}@{version}</code><p>{String(scan.decision_reason || "Review recorded evidence.")}</p></div><div className={`verdictPanel ${decision}`}><span>Install decision</span><strong>{decision}</strong><p>{decisionAction(decision)}</p></div></section>
    <nav className="packageTabs versionTabs"><a href="#overview">Overview</a><a href="#alerts">Alerts <b>{findings.length}</b></a><a href="#capabilities">Capabilities <b>{Object.keys(capabilities).length}</b></a><a href="#dependencies">Dependencies <b>{dependencies.length}</b></a><a href="#files">Files <b>{files.length}</b></a><a href="#changes">Changes</a><a href="#evidence">Scan evidence</a></nav>
    <section id="overview" className="versionOverview"><div className="bottomLine"><span>Bottom line</span><h2>{decisionHeadline(decision)}</h2><p>{plainLanguage(findings, capabilities)}</p><div><strong>Risk priority {Number(scan.risk_score || 0)}</strong><strong>Malware evidence {Number(scan.malware_score || 0)}</strong><strong>Coverage {Number(scan.coverage_percent || 0)}%</strong></div></div><div className="artifactSeal"><ShieldCheck/><span>Artifact SHA-256</span><code>{String(scan.artifact_sha256 || "unavailable")}</code><small>Scanned {formatDate(String(scan.scanned_at || ""))}</small></div></section>
    <IntelligenceScores risk={Number(scan.risk_score)} malware={Number(scan.malware_score)} coverage={Number(scan.coverage_percent)} dimensions={dimensions}/>
    <section id="alerts" className="intelligenceSection"><SectionHeading eyebrow="Alerts" title="Evidence requiring a decision" detail="Actionable findings are separated from context so common extension capabilities are not mislabeled as malware."/><div className="alertList">{findings.length ? findings.map((finding) => <article key={String(finding.id)}><span className={`severity ${String(finding.severity).toLowerCase()}`}>{String(finding.severity)}</span><div><strong>{String(finding.summary)}</strong><code>{String(finding.rule_id)}</code><p>{String(finding.recommendation || "Review the evidence and publisher intent.")}</p><small>{String(finding.evidence_class)} evidence · {String(finding.actionability)}</small></div>{Array.isArray(finding.file_refs) && finding.file_refs[0] ? <a href="#files"><FileCode2 size={16}/>{String(finding.file_refs[0])}</a> : null}</article>) : <Empty icon={<CircleCheck/>} text="No alerts crossed the active ruleset."/>}</div></section>
    <section id="capabilities" className="intelligenceSection"><SectionHeading eyebrow="Capability map" title="What the extension can access" detail="Capabilities describe power, not intent. Review whether each one matches the extension’s stated purpose."/><div className="capabilityGrid">{Object.entries(capabilities).map(([key, value]) => <article key={key}>{capabilityIcon(key)}<div><strong>{key.replaceAll("_", " ")}</strong><p>{Array.isArray(value.evidence) ? `${value.evidence.length} evidence location(s)` : "Declared or detected capability"}</p></div></article>)}</div></section>
    <section id="dependencies" className="intelligenceSection"><SectionHeading eyebrow="Dependency inventory" title="Runtime supply chain" detail="Direct and transitive packages are kept separate and tied to the scanned artifact."/><div className="dependencyTable"><div><span>Package</span><span>Resolved version</span><span>Relationship</span><span>Advisories</span></div>{dependencies.map((dependency) => <article key={`${dependency.name}@${dependency.version}`}><strong>{String(dependency.name)}</strong><code>{String(dependency.version)}</code><span>{String(dependency.relationship)}</span><span>{Array.isArray(dependency.advisories) ? dependency.advisories.length : 0}</span></article>)}</div></section>
    <section id="files" className="intelligenceSection"><SectionHeading eyebrow="Artifact explorer" title="Files inside the published VSIX" detail="Paths, sizes and hashes come from the exact artifact; extension code was not executed."/><div className="fileExplorer"><div className="fileToolbar"><span>/</span><span>{files.length} files</span></div>{files.slice(0, 500).map((file) => <div key={String(file.path)}><FileCode2 size={15}/><code>{String(file.path)}</code><span>{formatBytes(Number(file.size_bytes || 0))}</span><small>{String(file.sha256).slice(0, 12)}</small></div>)}</div>{files.length > 500 ? <p className="tableNote">Showing the first 500 paths. The canonical report retains the complete inventory.</p> : null}</section>
    <section id="changes" className="intelligenceSection"><SectionHeading eyebrow="Version intelligence" title="What changed from the baseline" detail="New capabilities and dependencies deserve attention even when neither version is malicious."/><DiffView diff={(scan.baseline_diff || {}) as Record<string, unknown>}/></section>
    <section id="evidence" className="intelligenceSection evidenceScope"><SectionHeading eyebrow="Scan evidence" title="What was actually assessed" detail="This technical scope supports the decision; it is not the decision itself."/><ProviderScope scan={scan}/></section>
  </main>;
}

function VersionCrumb({ id, name, version }: { id: string; name: string; version: string }) { return <div className="versionCrumb"><Link href="/catalog">Catalog</Link><ChevronRight/><Link href={`/extensions/${encodeURIComponent(id)}`}>{name}</Link><ChevronRight/><strong>{version}</strong></div>; }
function SectionHeading({ eyebrow, title, detail }: { eyebrow: string; title: string; detail: string }) { return <div className="sectionLabel"><span>{eyebrow}</span><h2>{title}</h2><p>{detail}</p></div>; }
function Empty({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="intelligenceEmpty">{icon}<p>{text}</p></div>; }
function decisionAction(decision: string) { return decision === "allow" ? "Approved by the active policy for this hash." : decision === "block" ? "Do not install or retain this artifact." : decision === "review" ? "Verify the highlighted behavior before approval." : "Required analysis is missing; do not approve."; }
function decisionHeadline(decision: string) { return decision === "allow" ? "No evidence crossed the review policy." : decision === "block" ? "Confirmed or high-confidence evidence requires blocking." : decision === "review" ? "Sensitive behavior needs human context." : "The scanner cannot make a complete trust decision."; }
function plainLanguage(findings: Array<Record<string, unknown>>, capabilities: Record<string, unknown>) { const cap = Object.keys(capabilities).map((item) => item.replaceAll("_", " ")); return findings.length ? `The scanner recorded ${findings.length} finding${findings.length === 1 ? "" : "s"}${cap.length ? ` and detected ${cap.slice(0, 3).join(", ")} capability` : ""}. Read the evidence below before installation.` : "The completed ruleset recorded no actionable findings for this exact artifact. Future versions require a new decision."; }
function capabilityIcon(key: string) { if (key.includes("network")) return <Network/>; if (key.includes("shell") || key.includes("process")) return <Terminal/>; if (key.includes("dependency")) return <Package/>; return <Box/>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "Unknown" : new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(date); }
function formatBytes(value: number) { if (value < 1024) return `${value} B`; if (value < 1024 ** 2) return `${(value / 1024).toFixed(1)} KB`; return `${(value / 1024 ** 2).toFixed(1)} MB`; }
function DiffView({ diff }: { diff: Record<string, unknown> }) { const changed = Boolean(diff.baseline_changed); const groups = [["New findings", diff.added_findings], ["New capabilities", diff.added_capabilities], ["New dependencies", diff.added_dependencies], ["Removed findings", diff.removed_findings]] as const; return <div className={`diffPanel ${changed ? "changed" : "unchanged"}`}><div>{changed ? <AlertTriangle/> : <GitCompareArrows/>}<strong>{changed ? "Security-relevant changes detected" : "No earlier scanned baseline"}</strong><p>{changed ? `${String(diff.previous_version || "previous")} → ${String(diff.current_version || "current")}` : "Scan another version to create a release comparison."}</p></div>{groups.map(([label, values]) => Array.isArray(values) && values.length ? <article key={label}><span>{label}</span>{values.map((value) => <code key={String(value)}>{String(value)}</code>)}</article> : null)}</div>; }
function ProviderScope({ scan }: { scan: Record<string, unknown> }) { const providers = (scan.provider_coverage || {}) as Record<string, Record<string, unknown>>; return <div className="scopePanel"><div><span>Profile</span><strong>{String(scan.profile || "deep")}</strong><p>Required analyzers must complete for a complete decision.</p></div>{Object.entries(providers).map(([name, provider]) => <div key={name}><span>{name.replaceAll("_", " ")}</span><strong className={provider.status === "completed" ? "scopeComplete" : "scopeMissing"}>{String(provider.status || "unknown")}</strong><p>{Number(provider.finding_count || 0)} normalized findings</p></div>)}</div>; }
