"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ClipboardCheck, ExternalLink, UserRound, Users } from "lucide-react";
import { browserDb } from "@/lib/supabase";

export default function TeamPage({ params }: { params: Promise<{ id: string }> }) {
  const db = browserDb(); const [id, setId] = useState(""); const [data, setData] = useState<Record<string, unknown> | null>(null); const [message, setMessage] = useState("Loading team…");
  useEffect(() => { void params.then(({ id: value }) => { setId(value); void db?.auth.getSession().then(({ data: session }) => { const token = session.session?.access_token; if (!token) { setMessage("Sign in to open this team."); return; } void fetch(`/api/teams/${value}`, { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { const body = await response.json(); if (!response.ok) setMessage(body.error); else { setData(body); setMessage(""); } }); }); }); }, [params, db]);
  const team = (data?.team || {}) as Record<string, unknown>; const members = (data?.members || []) as Array<Record<string, unknown>>; const watchlist = (data?.watchlist || []) as Array<Record<string, unknown>>; const triage = (data?.triage || []) as Array<Record<string, unknown>>;
  return <main className="teamPage"><Link className="backLink" href="/workspace"><ArrowLeft/> Workspace</Link><section className="teamHead"><div><span>Team workspace</span><h1>{String(team.name || "Security team")}</h1><p>Shared extension ownership, finding decisions and reviewer assignments.</p></div><Users size={38}/></section>{message ? <div className="workspaceMessage">{message}</div> : null}<section className="teamStats"><div><strong>{watchlist.length}</strong><span>watched extensions</span></div><div><strong>{triage.length}</strong><span>triaged findings</span></div><div><strong>{members.length}</strong><span>members</span></div></section><section className="teamColumns"><div><h2>Extension watchlist</h2>{watchlist.map((item) => <Link key={String(item.extension_id)} href={`/extensions/${encodeURIComponent(String(item.extension_id))}`}><strong>{String(item.extension_id)}</strong><ExternalLink/></Link>)}</div><div><h2>Finding queue</h2>{triage.map((item) => { const finding = (item.findings || {}) as Record<string, unknown>; return <article key={`${item.scan_id}-${item.finding_id}`}><ClipboardCheck/><div><strong>{String(finding.summary || item.finding_id)}</strong><span>{String(item.status).replaceAll("_", " ")} · {String(finding.severity || "")}</span></div></article>; })}</div><aside><h2>Members</h2>{members.map((member) => <div key={String(member.user_id)}><UserRound/><span>{String(((member.profiles || {}) as Record<string, unknown>).display_name || "Member")}</span><b>{String(member.role)}</b></div>)}</aside></section><span hidden>{id}</span></main>;
}
