"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, Bell, Clock3, Plus, ScanSearch, ShieldCheck } from "lucide-react";
import { browserDb } from "@/lib/supabase";

type Watchlist={id:string;name:string;watchlist_items?:Array<{extension_id:string;created_at:string;extensions?:{display_name?:string;icon_url?:string}}>};
type Job={id:string;extension_id:string;version:string;status:string;created_at:string;completed_at?:string|null;error?:string|null};
export default function WorkspacePage(){const db=useMemo(()=>browserDb(),[]);const[lists,setLists]=useState<Watchlist[]>([]);const[jobs,setJobs]=useState<Job[]>([]);const[name,setName]=useState("");const[state,setState]=useState<"loading"|"ready"|"signed-out"|"error">("loading");const[message,setMessage]=useState("");
useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
async function load(){if(!db)return setState("error");const{data:{user}}=await db.auth.getUser();if(!user)return setState("signed-out");const[watch,history]=await Promise.all([db.from("watchlists").select("*,watchlist_items(extension_id,created_at,extensions(display_name,icon_url))").order("created_at"),db.from("scan_jobs").select("id,extension_id,version,status,created_at,completed_at,error").order("created_at",{ascending:false}).limit(20)]);if(watch.error||history.error){setMessage(watch.error?.message||history.error?.message||"Workspace could not be loaded.");return setState("error")}setLists(watch.data||[]);setJobs(history.data||[]);setState("ready")}
async function createList(){if(!db||!name.trim())return;const{data:{user}}=await db.auth.getUser();if(!user)return;const result=await db.from("watchlists").insert({owner_id:user.id,name:name.trim().slice(0,80)});if(result.error)setMessage(result.error.message);else{setName("");await load()}}
if(state==="signed-out")return <main className="workspacePage"><section className="workspaceSignedOut"><ShieldCheck/><span>Personal security workspace</span><h1>Sign in to keep decisions and release changes together.</h1><p>Public intelligence remains open. An account adds scan history, watchlists and monitoring for the extensions you use.</p><Link className="button buttonDark" href="/account?next=/workspace">Sign in <ArrowRight/></Link></section></main>;
return <main className="workspacePage"><section className="workspaceHead"><div><span>Personal workspace</span><h1>Your extension security activity.</h1><p>Return to scans, watch exact extensions, and see which releases still need attention.</p></div><div className="workspaceActions"><Link className="button buttonDark" href="/scan"><ScanSearch/> New Deep Scan</Link><Link className="button buttonQuiet" href="/catalog">Browse catalog</Link></div></section>{state==="loading"?<div className="workspaceMessage">Loading your workspace…</div>:null}{message?<div className="workspaceMessage">{message}</div>:null}<section className="workspaceSummary"><article><ScanSearch/><span>Recent scans</span><strong>{jobs.length}</strong><p>{jobs.filter(x=>["queued","running"].includes(x.status)).length} currently processing</p></article><article><Bell/><span>Watched extensions</span><strong>{lists.reduce((n,l)=>n+(l.watchlist_items?.length||0),0)}</strong><p>Across {lists.length} personal watchlist{lists.length===1?"":"s"}</p></article><article><Clock3/><span>Needs attention</span><strong>{jobs.filter(x=>["failed","incomplete"].includes(x.status)).length}</strong><p>Failed or incomplete analysis</p></article></section><section className="workspaceSection"><div className="workspaceSectionHead"><div><span>Scan activity</span><h2>Recent Deep Scans</h2></div></div><div className="personalScanRows">{jobs.map(job=><article key={job.id}><Status value={job.status}/><div><strong>{job.extension_id}</strong><code>@{job.version}</code></div><span>{formatDate(job.created_at)}</span><Link href={`/extensions/${encodeURIComponent(job.extension_id)}/versions/${encodeURIComponent(job.version)}`}>Open <ArrowRight/></Link></article>)}{state==="ready"&&!jobs.length?<Empty title="No Deep Scans yet" detail="Choose any published extension and exact version to start your history." href="/catalog"/>:null}</div></section><section className="workspaceSection"><div className="workspaceSectionHead"><div><span>Monitoring</span><h2>Personal watchlists</h2></div><div className="createRow"><input value={name} onChange={e=>setName(e.target.value)} placeholder="New watchlist"/><button className="iconButton" onClick={()=>void createList()} title="Create watchlist"><Plus/></button></div></div><div className="watchlistBlocks">{lists.map(list=><article key={list.id}><header><div><strong>{list.name}</strong><span>{list.watchlist_items?.length||0} extensions</span></div><Bell/></header>{list.watchlist_items?.slice(0,6).map(item=><Link key={item.extension_id} href={`/extensions/${encodeURIComponent(item.extension_id)}`}><span>{item.extensions?.display_name||item.extension_id}</span><code>{item.extension_id}</code><ArrowRight/></Link>)}{!list.watchlist_items?.length?<p>Add an extension from its intelligence page.</p>:null}</article>)}</div></section></main>}
function Status({value}:{value:string}){return <span className={`scanJobStatus ${value}`}>{value}</span>}function formatDate(v:string){return new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(new Date(v))}function Empty({title,detail,href}:{title:string;detail:string;href:string}){return <div className="workspaceEmpty"><ShieldCheck/><strong>{title}</strong><p>{detail}</p><Link href={href}>Get started <ArrowRight/></Link></div>}
