"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Plus, Users } from "lucide-react";
import { browserDb } from "@/lib/supabase";

type Team = { team_id: string; role: string; teams: { name?: string; slug?: string } | null };
type Watchlist = { id: string; name: string; watchlist_items?: Array<{ extension_id: string }> };
export default function WorkspacePage() {
  const db = browserDb(); const [token, setToken] = useState(""); const [watchlists, setWatchlists] = useState<Watchlist[]>([]); const [teams, setTeams] = useState<Team[]>([]); const [name, setName] = useState(""); const [message, setMessage] = useState("Loading workspace…");
  useEffect(() => { void db?.auth.getSession().then(({ data }) => { const access = data.session?.access_token || ""; setToken(access); if (access) void load(access); else setMessage("Sign in to open your workspace."); }); }, [db]);
  async function load(access: string) { const headers = { Authorization: `Bearer ${access}` }; const [w, t] = await Promise.all([fetch("/api/watchlists", { headers }), fetch("/api/teams", { headers })]); const wb = await w.json(); const tb = await t.json(); setWatchlists(wb.watchlists || []); setTeams(tb.teams || []); setMessage(""); }
  async function create(kind: "watchlist"|"team") { if (!token || !name.trim()) return; const response = await fetch(kind === "team" ? "/api/teams" : "/api/watchlists", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const body = await response.json(); if (!response.ok) setMessage(body.error || "Creation failed."); else { setName(""); await load(token); } }
  return <main className="workspacePage"><section className="workspaceHead"><div><span>Security workspace</span><h1>Extensions your team is responsible for.</h1><p>Track exact versions, preserve review decisions and keep capability changes visible.</p></div><Link className="button buttonDark" href="/catalog">Add from catalog <ArrowRight/></Link></section>{message ? <div className="workspaceMessage">{message} {!token ? <Link href="/account">Open account</Link> : null}</div> : null}<section className="workspaceSection"><div className="workspaceSectionHead"><div><span>Personal</span><h2>Watchlists</h2></div><CreateRow value={name} setValue={setName} action={() => void create("watchlist")} label="New watchlist"/></div><div className="workspaceRows">{watchlists.map((list) => <article key={list.id}><strong>{list.name}</strong><span>{list.watchlist_items?.length || 0} extensions</span><ArrowRight/></article>)}</div></section><section className="workspaceSection" id="teams"><div className="workspaceSectionHead"><div><span>Shared</span><h2>Teams</h2></div><CreateRow value={name} setValue={setName} action={() => void create("team")} label="New team"/></div><div className="workspaceRows">{teams.map((membership) => <Link href={`/workspace/teams/${membership.team_id}`} className="workspaceTeamRow" key={membership.team_id}><Users/><strong>{membership.teams?.name || "Team"}</strong><span>{membership.role}</span><ArrowRight/></Link>)}</div></section></main>;
}
function CreateRow({ value, setValue, action, label }: { value: string; setValue: (value: string) => void; action: () => void; label: string }) { return <div className="createRow"><input value={value} onChange={(event) => setValue(event.target.value)} placeholder={label}/><button className="iconButton" onClick={action} title={label}><Plus/></button></div>; }
